#!/usr/bin/env node
/**
 * data/tank_visuals.csv -> assets/scripts/core/TankVisualDB.ts
 *
 * Keep tank presentation values in CSV so scale, offsets, trims and pivots can
 * be tuned without editing BattleScene rendering code.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'tank_visuals.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'TankVisualDB.ts');

const REQUIRED_KINDS = ['sherman', 'tiger', 'panzer4', 'panzer3', 'truck'];
const SPLIT_KINDS = ['sherman', 'tiger', 'panzer4', 'panzer3'];
const NUM_FIELDS = [
  'fitScale',
  'offsetForward',
  'offsetRight',
  'aspectRatioMul',
  'hullFitScale',
  'turretScale',
  'hullOffsetForward',
  'hullOffsetRight',
  'turretOffsetForward',
  'turretOffsetRight',
  'turretLocalOffsetForward',
  'turretLocalOffsetRight',
  'topTrimX',
  'topTrimY',
  'topTrimW',
  'topTrimH',
  'turretTrimX',
  'turretTrimY',
  'turretTrimW',
  'turretTrimH',
  'turretPivotX',
  'turretPivotY',
  'turretSpritePivotX',
  'turretSpritePivotY',
  'destroyedOffsetForward',
  'destroyedOffsetRight',
];
const STRING_FIELDS = [
  'topSpritePath',
  'hullSpritePath',
  'turretSpritePath',
  'destroyedSpritePath',
];

function readCsvSmart(filePath) {
  const buf = fs.readFileSync(filePath);
  const hasBOM = buf.length >= 3 && buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF;

  let text;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(buf);
  } catch (_) {
    text = new TextDecoder('gbk').decode(buf);
  }

  if (!hasBOM) {
    fs.writeFileSync(filePath, Buffer.concat([
      Buffer.from([0xEF, 0xBB, 0xBF]),
      Buffer.from(text, 'utf8'),
    ]));
  }
  return text;
}

function detectDelimiter(text) {
  const firstLine = text.replace(/^\uFEFF/, '').split(/\r?\n/, 1)[0] || '';
  const commaCount = (firstLine.match(/,/g) || []).length;
  const tabCount = (firstLine.match(/\t/g) || []).length;
  return tabCount > commaCount ? '\t' : ',';
}

function parseCSV(text) {
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
  const delimiter = detectDelimiter(text);
  const rows = [];
  let row = [];
  let cur = '';
  let inQuote = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuote) {
      if (c === '"') {
        if (text[i + 1] === '"') { cur += '"'; i++; }
        else inQuote = false;
      } else {
        cur += c;
      }
    } else if (c === '"' && cur === '') {
      inQuote = true;
    } else if (c === delimiter) {
      row.push(cur);
      cur = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(cur);
      cur = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else {
      cur += c;
    }
  }
  if (cur !== '' || row.length) {
    row.push(cur);
    if (row.length > 1 || row[0] !== '') rows.push(row);
  }
  return rows;
}

function toRecords(rows) {
  if (!rows.length) throw new Error('CSV is empty');
  const headers = rows[0].map(h => h.trim());
  return rows.slice(1).map((r, idx) => {
    const obj = {};
    headers.forEach((h, i) => { obj[h] = (r[i] ?? '').trim(); });
    obj.__row = idx + 2;
    return obj;
  });
}

function numberOrThrow(rec, field) {
  const raw = rec[field];
  if (raw === '' || raw === undefined) {
    throw new Error(`row ${rec.__row} ${rec.kind || '?'}: field ${field} is empty`);
  }
  const n = Number(raw);
  if (!Number.isFinite(n)) {
    throw new Error(`row ${rec.__row} ${rec.kind || '?'}: field ${field}="${raw}" is not a number`);
  }
  return n;
}

function emitNum(n) {
  return Number.isInteger(n) ? String(n) : String(n);
}

function emitString(s) {
  return JSON.stringify(s);
}

function build() {
  const records = toRecords(parseCSV(readCsvSmart(CSV_PATH)));
  const byKind = new Map();

  for (const rec of records) {
    if (!rec.kind) throw new Error(`row ${rec.__row}: kind is empty`);
    if (!REQUIRED_KINDS.includes(rec.kind)) {
      throw new Error(`row ${rec.__row}: unknown kind "${rec.kind}"`);
    }
    if (byKind.has(rec.kind)) {
      throw new Error(`row ${rec.__row}: duplicate kind "${rec.kind}"`);
    }
    for (const field of NUM_FIELDS) {
      rec[field] = numberOrThrow(rec, field);
    }
    for (const field of STRING_FIELDS) {
      rec[field] = rec[field] || '';
    }
    byKind.set(rec.kind, rec);
  }

  for (const kind of REQUIRED_KINDS) {
    if (!byKind.has(kind)) throw new Error(`CSV is missing kind "${kind}"`);
  }

  const lines = [];
  lines.push('/**');
  lines.push(' * Tank presentation database. Auto-generated; do not edit this file.');
  lines.push(' *');
  lines.push(' * Source: data/tank_visuals.csv');
  lines.push(' * Rebuild: node tools/buildTankVisualDB.js');
  lines.push(' */');
  lines.push('');
  lines.push("import { UnitKind } from './types';");
  lines.push('');
  lines.push("export type TankVisualKind = Extract<UnitKind, 'sherman' | 'panzer4' | 'panzer3' | 'tiger' | 'truck'>;");
  lines.push("export type SplitTankKind = Extract<UnitKind, 'sherman' | 'tiger' | 'panzer4' | 'panzer3'>;");
  lines.push('export const TANK_VISUAL_KINDS: readonly TankVisualKind[] = [\'sherman\', \'tiger\', \'panzer4\', \'panzer3\', \'truck\'];');
  lines.push('export const SPLIT_TANK_KINDS: readonly SplitTankKind[] = [\'sherman\', \'tiger\', \'panzer4\', \'panzer3\'];');
  lines.push('');
  lines.push('export interface TankVisualAssetConfig {');
  lines.push('  topSpritePath: string;');
  lines.push('  hullSpritePath: string;');
  lines.push('  turretSpritePath: string;');
  lines.push('  destroyedSpritePath: string;');
  lines.push('}');
  lines.push('');
  lines.push('export interface TankVisualConfig {');
  lines.push('  fitScale: number;');
  lines.push('  offsetForward: number;');
  lines.push('  offsetRight: number;');
  lines.push('  aspectRatioMul: number;');
  lines.push('  destroyedOffsetForward: number;');
  lines.push('  destroyedOffsetRight: number;');
  lines.push('}');
  lines.push('');
  lines.push('export interface SplitTankVisualConfig {');
  lines.push('  hullFitScale: number;');
  lines.push('  turretScale: number;');
  lines.push('  hullOffsetForward: number;');
  lines.push('  hullOffsetRight: number;');
  lines.push('  turretOffsetForward: number;');
  lines.push('  turretOffsetRight: number;');
  lines.push('  turretLocalOffsetForward: number;');
  lines.push('  turretLocalOffsetRight: number;');
  lines.push('}');
  lines.push('');
  lines.push('export interface SplitTankGeometryConfig {');
  lines.push('  topTrim: { x: number; y: number; w: number; h: number };');
  lines.push('  turretTrim: { x: number; y: number; w: number; h: number };');
  lines.push('  pivot: { bodyX: number; bodyY: number; spriteX: number; spriteY: number };');
  lines.push('}');
  lines.push('');
  lines.push('const TANK_VISUAL_DEFAULT: TankVisualConfig = {');
  lines.push('  fitScale: 1,');
  lines.push('  offsetForward: 0,');
  lines.push('  offsetRight: 0,');
  lines.push('  aspectRatioMul: 1,');
  lines.push('  destroyedOffsetForward: 0,');
  lines.push('  destroyedOffsetRight: 0,');
  lines.push('};');
  lines.push('');
  lines.push('const TANK_VISUAL_ASSET_CONFIG: Record<TankVisualKind, TankVisualAssetConfig> = {');
  for (const kind of REQUIRED_KINDS) {
    const r = byKind.get(kind);
    lines.push(`  ${kind}: { topSpritePath: ${emitString(r.topSpritePath)}, hullSpritePath: ${emitString(r.hullSpritePath)}, turretSpritePath: ${emitString(r.turretSpritePath)}, destroyedSpritePath: ${emitString(r.destroyedSpritePath)} },`);
  }
  lines.push('};');
  lines.push('');
  lines.push('const TANK_VISUAL_CONFIG: Record<TankVisualKind, TankVisualConfig> = {');
  for (const kind of REQUIRED_KINDS) {
    const r = byKind.get(kind);
    lines.push(`  ${kind}: { fitScale: ${emitNum(r.fitScale)}, offsetForward: ${emitNum(r.offsetForward)}, offsetRight: ${emitNum(r.offsetRight)}, aspectRatioMul: ${emitNum(r.aspectRatioMul)}, destroyedOffsetForward: ${emitNum(r.destroyedOffsetForward)}, destroyedOffsetRight: ${emitNum(r.destroyedOffsetRight)} },`);
  }
  lines.push('};');
  lines.push('');
  lines.push('const SPLIT_TANK_VISUAL_CONFIG: Record<SplitTankKind, SplitTankVisualConfig> = {');
  for (const kind of SPLIT_KINDS) {
    const r = byKind.get(kind);
    lines.push(`  ${kind}: { hullFitScale: ${emitNum(r.hullFitScale)}, turretScale: ${emitNum(r.turretScale)}, hullOffsetForward: ${emitNum(r.hullOffsetForward)}, hullOffsetRight: ${emitNum(r.hullOffsetRight)}, turretOffsetForward: ${emitNum(r.turretOffsetForward)}, turretOffsetRight: ${emitNum(r.turretOffsetRight)}, turretLocalOffsetForward: ${emitNum(r.turretLocalOffsetForward)}, turretLocalOffsetRight: ${emitNum(r.turretLocalOffsetRight)} },`);
  }
  lines.push('};');
  lines.push('');
  lines.push('const SPLIT_TANK_GEOMETRY_CONFIG: Record<SplitTankKind, SplitTankGeometryConfig> = {');
  for (const kind of SPLIT_KINDS) {
    const r = byKind.get(kind);
    lines.push(`  ${kind}: {`);
    lines.push(`    topTrim: { x: ${emitNum(r.topTrimX)}, y: ${emitNum(r.topTrimY)}, w: ${emitNum(r.topTrimW)}, h: ${emitNum(r.topTrimH)} },`);
    lines.push(`    turretTrim: { x: ${emitNum(r.turretTrimX)}, y: ${emitNum(r.turretTrimY)}, w: ${emitNum(r.turretTrimW)}, h: ${emitNum(r.turretTrimH)} },`);
    lines.push(`    pivot: { bodyX: ${emitNum(r.turretPivotX)}, bodyY: ${emitNum(r.turretPivotY)}, spriteX: ${emitNum(r.turretSpritePivotX)}, spriteY: ${emitNum(r.turretSpritePivotY)} },`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('export function tankVisualAssetConfigOf(kind: TankVisualKind): TankVisualAssetConfig {');
  lines.push('  return TANK_VISUAL_ASSET_CONFIG[kind];');
  lines.push('}');
  lines.push('');
  lines.push('export function tankVisualConfigOf(kind: UnitKind): TankVisualConfig {');
  lines.push("  if (kind === 'sherman' || kind === 'tiger' || kind === 'panzer4' || kind === 'panzer3' || kind === 'truck') {");
  lines.push('    return TANK_VISUAL_CONFIG[kind];');
  lines.push('  }');
  lines.push('  return TANK_VISUAL_DEFAULT;');
  lines.push('}');
  lines.push('');
  lines.push('export function splitTankVisualConfigOf(kind: SplitTankKind): SplitTankVisualConfig {');
  lines.push('  return SPLIT_TANK_VISUAL_CONFIG[kind];');
  lines.push('}');
  lines.push('');
  lines.push('export function splitTankGeometryConfigOf(kind: SplitTankKind): SplitTankGeometryConfig {');
  lines.push('  return SPLIT_TANK_GEOMETRY_CONFIG[kind];');
  lines.push('}');
  lines.push('');

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildTankVisualDB] OK  ${records.length} rows -> ${path.relative(ROOT, OUT_PATH)}`);
}

try {
  build();
} catch (e) {
  console.error('[buildTankVisualDB] failed:', e.message);
  process.exit(1);
}
