#!/usr/bin/env node
/**
 * data/damage_table.csv -> assets/scripts/core/DamageTableDB.ts
 *
 * Source of truth for hardcore direction-specific damage effects.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { readCsvRowsSmart } = require('./csvSmart');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'damage_table.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'DamageTableDB.ts');

const REQUIRED_HEADERS = ['targetClass', 'damageCheckType', 'die', 'effects', 'notes'];
const TARGET_CLASSES = ['german_tank', 'us_tank', 'protagonist'];
const DAMAGE_CHECK_TYPES = ['front', 'right', 'left', 'rear'];
const EFFECTS = ['destroyed', 'fire', 'turret', 'paralyzed', 'radio'];
const CREW_ROLES = ['commander', 'loader', 'gunner', 'driver', 'coDriver'];

function js(value) {
  return JSON.stringify(value);
}

function toRecords(rows) {
  if (!rows.length) throw new Error('CSV is empty');
  const headers = rows[0].map(h => h.trim().replace(/^\uFEFF/, ''));
  for (const h of REQUIRED_HEADERS) {
    if (!headers.includes(h)) throw new Error(`missing required header "${h}"`);
  }
  return rows.slice(1).map((row, idx) => {
    const rec = {};
    headers.forEach((h, i) => { rec[h] = (row[i] ?? '').trim(); });
    rec.__row = idx + 2;
    return rec;
  });
}

function parseDie(rec) {
  const n = Number(rec.die);
  if (!Number.isInteger(n) || n < 1 || n > 6) {
    throw new Error(`row ${rec.__row}: die="${rec.die}" must be 1..6`);
  }
  return n;
}

function parseEffectToken(rec, token) {
  const crewMatch = /^crew\(([^)]*)\)$/.exec(token);
  if (crewMatch) {
    const crew = crewMatch[1].split('|').map(s => s.trim()).filter(Boolean);
    if (!crew.length) throw new Error(`row ${rec.__row}: crew() must list at least one role`);
    for (const role of crew) {
      if (!CREW_ROLES.includes(role)) {
        throw new Error(`row ${rec.__row}: unknown crew role "${role}"`);
      }
    }
    return { kind: 'crew', crew };
  }
  if (!EFFECTS.includes(token)) {
    throw new Error(`row ${rec.__row}: unknown effect "${token}"`);
  }
  return { kind: token };
}

function parseEffects(rec) {
  if (!rec.effects) throw new Error(`row ${rec.__row}: effects is empty`);
  return rec.effects.split('>').map(groupText => {
    const tokens = groupText.split('+').map(s => s.trim()).filter(Boolean);
    if (!tokens.length) throw new Error(`row ${rec.__row}: empty priority group in "${rec.effects}"`);
    return tokens.map(token => parseEffectToken(rec, token));
  });
}

function build() {
  const rows = readCsvRowsSmart(CSV_PATH, {
    toolName: 'buildDamageTableDB',
    requiredHeaders: REQUIRED_HEADERS,
  });
  const records = toRecords(rows);
  const byKey = new Map();

  for (const rec of records) {
    if (!TARGET_CLASSES.includes(rec.targetClass)) {
      throw new Error(`row ${rec.__row}: targetClass="${rec.targetClass}" must be ${TARGET_CLASSES.join(' / ')}`);
    }
    if (!DAMAGE_CHECK_TYPES.includes(rec.damageCheckType)) {
      throw new Error(`row ${rec.__row}: damageCheckType="${rec.damageCheckType}" must be ${DAMAGE_CHECK_TYPES.join(' / ')}`);
    }
    const die = parseDie(rec);
    const key = `${rec.targetClass}|${rec.damageCheckType}|${die}`;
    if (byKey.has(key)) throw new Error(`row ${rec.__row}: duplicate ${key}`);
    byKey.set(key, { ...rec, die, groups: parseEffects(rec) });
  }

  for (const targetClass of TARGET_CLASSES) {
    for (const damageCheckType of DAMAGE_CHECK_TYPES) {
      for (let die = 1; die <= 6; die++) {
        const key = `${targetClass}|${damageCheckType}|${die}`;
        if (!byKey.has(key)) throw new Error(`CSV missing ${key}`);
      }
    }
  }

  const lines = [];
  lines.push('/**');
  lines.push(' * Damage table DB - generated automatically. Do not edit this file by hand.');
  lines.push(' *');
  lines.push(' * Source: data/damage_table.csv');
  lines.push(' * Regenerate: node tools/buildDamageTableDB.js');
  lines.push(' */');
  lines.push('');
  lines.push("import type { DamageCheckType } from './AttackDirectionDB';");
  lines.push('');
  lines.push("export type DamageTargetClass = 'german_tank' | 'us_tank' | 'protagonist';");
  lines.push("export type DamageTableEffectKind = 'destroyed' | 'fire' | 'turret' | 'paralyzed' | 'radio' | 'crew';");
  lines.push("export type DamageTableCrewRole = 'commander' | 'loader' | 'gunner' | 'driver' | 'coDriver';");
  lines.push('');
  lines.push('export interface DamageTableEffect {');
  lines.push('  kind: DamageTableEffectKind;');
  lines.push('  crew?: DamageTableCrewRole[];');
  lines.push('}');
  lines.push('');
  lines.push('export interface DamageTableEntry {');
  lines.push('  targetClass: DamageTargetClass;');
  lines.push('  damageCheckType: DamageCheckType;');
  lines.push('  die: number;');
  lines.push('  groups: DamageTableEffect[][];');
  lines.push('  notes: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const DAMAGE_TABLE: Record<DamageTargetClass, Record<DamageCheckType, Record<number, DamageTableEntry>>> = {');
  for (const targetClass of TARGET_CLASSES) {
    lines.push(`  ${targetClass}: {`);
    for (const damageCheckType of DAMAGE_CHECK_TYPES) {
      lines.push(`    ${damageCheckType}: {`);
      for (let die = 1; die <= 6; die++) {
        const rec = byKey.get(`${targetClass}|${damageCheckType}|${die}`);
        lines.push(`      ${die}: { targetClass: '${targetClass}', damageCheckType: '${damageCheckType}', die: ${die}, groups: ${js(rec.groups)}, notes: ${js(rec.notes ?? '')} },`);
      }
      lines.push('    },');
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildDamageTableDB] OK ${records.length} rows -> ${path.relative(ROOT, OUT_PATH)}`);
}

try {
  build();
} catch (e) {
  console.error('[buildDamageTableDB] failed:', e.message);
  process.exit(1);
}
