#!/usr/bin/env node
/**
 * data/campaign_upgrades.csv -> assets/scripts/core/CampaignUpgradeDB.ts
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { readCsvRowsSmart } = require('./csvSmart');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'campaign_upgrades.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'CampaignUpgradeDB.ts');
const NUMBER_FIELDS = [
  'interiorVisionBonus', 'gunnerVisionBonus', 'hitThresholdModifier',
  'armorFrontSideBonus', 'armorRearSideBonus',
  'gunMantletArmorBonus',
  'mudAttackDiceBonus', 'mudMovementDiceBonus', 'mudMiscDiceBonus',
  'beachAttackDiceBonus', 'beachMovementDiceBonus', 'beachMiscDiceBonus', 'miscDiceBonus',
];
const BOOLEAN_FIELDS = [
  'ignoreDestroyed', 'ignoreCrewCheck', 'repairDiceCanFireSuppress',
  'movementDiceCanReverseDirection', 'smokeOnMiscPips2And4',
  'shootingDiceCanReload', 'mineDamageImmune', 'hiddenLongRangeUntargetable',
  'mechanicalFailureImmune', 'ignoreFirstAttackParalyzedPerSegment',
  'commanderShieldPerSegment', 'reviveCrewAtSegmentStart', 'carryLowestUnusedAttackDie',
];
const REQUIRED_HEADERS = ['id', 'nameKey', 'descriptionKey', ...NUMBER_FIELDS, ...BOOLEAN_FIELDS];

function build() {
  const rows = readCsvRowsSmart(CSV_PATH, {
    toolName: 'buildCampaignUpgradeDB',
    requiredHeaders: REQUIRED_HEADERS,
  });
  if (rows.length < 2) throw new Error('CSV has no upgrade rows');
  const headers = rows[0].map(h => h.trim().replace(/^\uFEFF/, ''));
  const seen = new Set();
  const records = rows.slice(1).filter(row => row.some(cell => String(cell ?? '').trim())).map((row, index) => {
    const rec = {};
    headers.forEach((header, i) => { rec[header] = String(row[i] ?? '').trim(); });
    const rowNo = index + 2;
    if (!/^[a-z][a-z0-9_]*$/.test(rec.id)) throw new Error(`row ${rowNo}: invalid id "${rec.id}"`);
    if (seen.has(rec.id)) throw new Error(`row ${rowNo}: duplicate id "${rec.id}"`);
    seen.add(rec.id);
    if (!rec.nameKey || !rec.descriptionKey) throw new Error(`row ${rowNo}: missing localization key`);
    for (const field of NUMBER_FIELDS) {
      const value = Number(rec[field]);
      if (!Number.isFinite(value)) throw new Error(`row ${rowNo}: ${field} must be numeric`);
      rec[field] = value;
    }
    for (const field of BOOLEAN_FIELDS) {
      if (rec[field] !== '0' && rec[field] !== '1') throw new Error(`row ${rowNo}: ${field} must be 0 or 1`);
      rec[field] = rec[field] === '1';
    }
    return rec;
  });
  if (records.length !== 19) throw new Error(`expected 19 upgrades, got ${records.length}`);

  const ids = records.map(rec => JSON.stringify(rec.id)).join(' | ');
  const lines = [
    '/**',
    ' * Campaign upgrade DB - generated automatically. Do not edit this file by hand.',
    ' *',
    ' * Source: data/campaign_upgrades.csv',
    ' * Regenerate: node tools/buildCampaignUpgradeDB.js',
    ' */',
    '',
    `export type CampaignUpgradeId = ${ids};`,
    '',
    'export interface CampaignUpgradeDefinition {',
    '  id: CampaignUpgradeId;',
    '  nameKey: string;',
    '  descriptionKey: string;',
    ...NUMBER_FIELDS.map(field => `  ${field}: number;`),
    ...BOOLEAN_FIELDS.map(field => `  ${field}: boolean;`),
    '}',
    '',
    'export const CAMPAIGN_UPGRADES: readonly CampaignUpgradeDefinition[] = [',
  ];
  for (const rec of records) {
    lines.push('  {');
    lines.push(`    id: ${JSON.stringify(rec.id)},`);
    lines.push(`    nameKey: ${JSON.stringify(rec.nameKey)},`);
    lines.push(`    descriptionKey: ${JSON.stringify(rec.descriptionKey)},`);
    for (const field of NUMBER_FIELDS) lines.push(`    ${field}: ${rec[field]},`);
    for (const field of BOOLEAN_FIELDS) lines.push(`    ${field}: ${rec[field]},`);
    lines.push('  },');
  }
  lines.push('];', '');
  lines.push('export const CAMPAIGN_UPGRADE_BY_ID = CAMPAIGN_UPGRADES.reduce((out, def) => {');
  lines.push('  out[def.id] = def;');
  lines.push('  return out;');
  lines.push('}, {} as Record<CampaignUpgradeId, CampaignUpgradeDefinition>);', '');
  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildCampaignUpgradeDB] OK ${records.length} rows -> ${path.relative(ROOT, OUT_PATH)}`);
}

try {
  build();
} catch (error) {
  console.error('[buildCampaignUpgradeDB] failed:', error.message);
  process.exit(1);
}
