#!/usr/bin/env node
/**
 * data/attack_direction_table.csv -> assets/scripts/core/AttackDirectionDB.ts
 *
 * Source of truth for incoming-fire angle rules. Angles are relative to the
 * target hull facing, clockwise positive, with 60 degrees meaning right-front.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { readCsvRowsSmart } = require('./csvSmart');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'attack_direction_table.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'AttackDirectionDB.ts');

const REQUIRED_HEADERS = ['position', 'incomingAngle', 'armor', 'damageCheckType', 'notes'];
const REQUIRED_ANGLES = [-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150, 180];
const ARMOR_FACES = ['front', 'frontSide', 'rearSide', 'rear'];
const DAMAGE_CHECK_TYPES = ['front', 'right', 'left', 'rear'];

function jsString(s) {
  return JSON.stringify(s ?? '');
}

function toRecords(rows) {
  if (!rows.length) throw new Error('CSV is empty');
  const headers = rows[0].map(h => h.trim().replace(/^\uFEFF/, ''));
  for (const h of REQUIRED_HEADERS) {
    if (!headers.includes(h)) throw new Error(`missing required header "${h}"`);
  }
  return rows.slice(1).map((row, idx) => {
    const rec = {};
    headers.forEach((h, i) => { rec[h] = (row[i] ?? '').trim(); });
    rec.__row = idx + 2;
    return rec;
  });
}

function intOrThrow(rec, field) {
  const raw = rec[field];
  const n = Number(raw);
  if (!Number.isInteger(n)) {
    throw new Error(`row ${rec.__row}: ${field}="${raw}" is not an integer`);
  }
  return n;
}

function build() {
  const rows = readCsvRowsSmart(CSV_PATH, {
    toolName: 'buildAttackDirectionDB',
    requiredHeaders: REQUIRED_HEADERS,
  });
  const records = toRecords(rows);

  const byAngle = new Map();
  for (const rec of records) {
    const angle = intOrThrow(rec, 'incomingAngle');
    if (!REQUIRED_ANGLES.includes(angle)) {
      throw new Error(`row ${rec.__row}: incomingAngle=${angle} must be one of ${REQUIRED_ANGLES.join(', ')}`);
    }
    if (byAngle.has(angle)) {
      throw new Error(`row ${rec.__row}: duplicate incomingAngle=${angle}`);
    }
    if (!ARMOR_FACES.includes(rec.armor)) {
      throw new Error(`row ${rec.__row}: armor="${rec.armor}" must be ${ARMOR_FACES.join(' / ')}`);
    }
    if (!DAMAGE_CHECK_TYPES.includes(rec.damageCheckType)) {
      throw new Error(`row ${rec.__row}: damageCheckType="${rec.damageCheckType}" must be ${DAMAGE_CHECK_TYPES.join(' / ')}`);
    }
    byAngle.set(angle, rec);
  }

  for (const angle of REQUIRED_ANGLES) {
    if (!byAngle.has(angle)) throw new Error(`CSV missing incomingAngle=${angle}`);
  }

  const lines = [];
  lines.push('/**');
  lines.push(' * Attack direction rules - generated automatically. Do not edit this file by hand.');
  lines.push(' *');
  lines.push(' * Source: data/attack_direction_table.csv');
  lines.push(' * Regenerate: node tools/buildAttackDirectionDB.js');
  lines.push(' */');
  lines.push('');
  lines.push("export type ArmorFace = 'front' | 'frontSide' | 'rearSide' | 'rear';");
  lines.push("export type DamageCheckType = 'front' | 'right' | 'left' | 'rear';");
  lines.push('');
  lines.push('export interface AttackDirectionRule {');
  lines.push('  position: string;');
  lines.push('  incomingAngle: number;');
  lines.push('  armorFace: ArmorFace;');
  lines.push('  damageCheckType: DamageCheckType;');
  lines.push('  notes: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const ATTACK_DIRECTION_RULES: Record<number, AttackDirectionRule> = {');
  for (const angle of REQUIRED_ANGLES) {
    const rec = byAngle.get(angle);
    lines.push(`  [${angle}]: { position: ${jsString(rec.position)}, incomingAngle: ${angle}, armorFace: '${rec.armor}', damageCheckType: '${rec.damageCheckType}', notes: ${jsString(rec.notes)} },`);
  }
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildAttackDirectionDB] OK ${records.length} rules -> ${path.relative(ROOT, OUT_PATH)}`);
}

try {
  build();
} catch (e) {
  console.error('[buildAttackDirectionDB] failed:', e.message);
  process.exit(1);
}
