#!/usr/bin/env node
/**
 * data/fire_check_table.csv -> assets/scripts/core/FireCheckDB.ts
 *
 * Source of truth for phase 5 fire check results.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { readCsvRowsSmart } = require('./csvSmart');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'fire_check_table.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'FireCheckDB.ts');

const REQUIRED_HEADERS = ['profile', 'die', 'effect', 'notes'];
const EFFECTS = ['destroyed', 'crewCheck', 'fire', 'turret', 'paralyzed', 'none'];

function js(value) {
  return JSON.stringify(value);
}

function toRecords(rows) {
  if (!rows.length) throw new Error('CSV is empty');
  const headers = rows[0].map(h => h.trim().replace(/^\uFEFF/, ''));
  for (const h of REQUIRED_HEADERS) {
    if (!headers.includes(h)) throw new Error(`missing required header "${h}"`);
  }
  return rows.slice(1).map((row, idx) => {
    const rec = {};
    headers.forEach((h, i) => { rec[h] = (row[i] ?? '').trim(); });
    rec.__row = idx + 2;
    return rec;
  });
}

function parseDie(rec) {
  const n = Number(rec.die);
  if (!Number.isInteger(n) || n < 1 || n > 6) {
    throw new Error(`row ${rec.__row}: die="${rec.die}" must be 1..6`);
  }
  return n;
}

function build() {
  const rows = readCsvRowsSmart(CSV_PATH, {
    toolName: 'buildFireCheckDB',
    requiredHeaders: REQUIRED_HEADERS,
  });
  const records = toRecords(rows);
  const profiles = Array.from(new Set(records.map(rec => rec.profile))).sort();
  if (!profiles.length) throw new Error('CSV has no profile rows');

  const byKey = new Map();
  for (const rec of records) {
    if (!rec.profile) throw new Error(`row ${rec.__row}: profile is empty`);
    const die = parseDie(rec);
    if (!EFFECTS.includes(rec.effect)) {
      throw new Error(`row ${rec.__row}: effect="${rec.effect}" must be ${EFFECTS.join(' / ')}`);
    }
    const key = `${rec.profile}|${die}`;
    if (byKey.has(key)) throw new Error(`row ${rec.__row}: duplicate ${key}`);
    byKey.set(key, { ...rec, die });
  }

  for (const profile of profiles) {
    for (let die = 1; die <= 6; die++) {
      const key = `${profile}|${die}`;
      if (!byKey.has(key)) throw new Error(`CSV missing ${key}`);
    }
  }

  const lines = [];
  lines.push('/**');
  lines.push(' * Fire check DB - generated automatically. Do not edit this file by hand.');
  lines.push(' *');
  lines.push(' * Source: data/fire_check_table.csv');
  lines.push(' * Regenerate: node tools/buildFireCheckDB.js');
  lines.push(' */');
  lines.push('');
  lines.push(`export type FireCheckProfile = ${profiles.map(p => js(p)).join(' | ')};`);
  lines.push(`export type FireCheckEffect = ${EFFECTS.map(e => js(e)).join(' | ')};`);
  lines.push('');
  lines.push('export interface FireCheckEntry {');
  lines.push('  profile: FireCheckProfile;');
  lines.push('  die: number;');
  lines.push('  effect: FireCheckEffect;');
  lines.push('  notes: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const FIRE_CHECK_TABLE: Record<FireCheckProfile, Record<number, FireCheckEntry>> = {');
  for (const profile of profiles) {
    lines.push(`  ${profile}: {`);
    for (let die = 1; die <= 6; die++) {
      const rec = byKey.get(`${profile}|${die}`);
      lines.push(`    ${die}: { profile: '${profile}', die: ${die}, effect: '${rec.effect}', notes: ${js(rec.notes ?? '')} },`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildFireCheckDB] OK ${records.length} rows -> ${path.relative(ROOT, OUT_PATH)}`);
}

try {
  build();
} catch (e) {
  console.error('[buildFireCheckDB] failed:', e.message);
  process.exit(1);
}
