#!/usr/bin/env node
/**
 * data/infantry_visuals.csv -> assets/scripts/core/InfantryVisualDB.ts
 *
 * Three-person infantry squad art and per-soldier scale multipliers.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { readCsvRowsSmart } = require('./csvSmart');

const ROOT = path.resolve(__dirname, '..');
const CSV_PATH = path.join(ROOT, 'data', 'infantry_visuals.csv');
const OUT_PATH = path.join(ROOT, 'assets', 'scripts', 'core', 'InfantryVisualDB.ts');
const KINDS = ['infantry', 'german_infantry', 'soviet_infantry', 'japanese_infantry', 'american_infantry'];
const FIELDS = ['sprite1Path', 'sprite1Scale', 'sprite2Path', 'sprite2Scale', 'sprite3Path', 'sprite3Scale'];

function build() {
  const rows = readCsvRowsSmart(CSV_PATH, {
    toolName: 'buildInfantryVisualDB',
    requiredHeaders: ['kind', ...FIELDS],
  });
  const headers = rows[0].map(h => h.trim().replace(/^\uFEFF/, ''));
  const records = rows.slice(1).map((row, index) => Object.fromEntries(headers.map((header, col) => [header, (row[col] ?? '').trim(),])));
  const byKind = new Map();
  for (const rec of records) {
    if (!KINDS.includes(rec.kind)) throw new Error(`unknown infantry visual kind "${rec.kind}"`);
    if (byKind.has(rec.kind)) throw new Error(`duplicate infantry visual kind "${rec.kind}"`);
    for (let i = 1; i <= 3; i++) {
      const pathValue = rec[`sprite${i}Path`];
      const scale = Number(rec[`sprite${i}Scale`]);
      if (!pathValue) throw new Error(`${rec.kind}: sprite${i}Path is empty`);
      if (!Number.isFinite(scale) || scale <= 0) throw new Error(`${rec.kind}: sprite${i}Scale must be a positive number`);
      rec[`sprite${i}Scale`] = scale;
    }
    byKind.set(rec.kind, rec);
  }
  for (const kind of KINDS) if (!byKind.has(kind)) throw new Error(`CSV is missing kind "${kind}"`);

  const lines = [
    '/**',
    ' * Infantry squad presentation database. Auto-generated; do not edit this file.',
    ' *',
    ' * Source: data/infantry_visuals.csv',
    ' * Rebuild: node tools/buildInfantryVisualDB.js',
    ' */',
    '',
    "import { UnitKind } from './types';",
    '',
    `export type InfantryVisualKind = Extract<UnitKind, ${KINDS.map(kind => `'${kind}'`).join(' | ')}>;`,
    `export const INFANTRY_VISUAL_KINDS: readonly InfantryVisualKind[] = [${KINDS.map(kind => `'${kind}'`).join(', ')}];`,
    '',
    'export interface InfantrySoldierVisualConfig {',
    '  spritePath: string;',
    '  scale: number;',
    '}',
    '',
    'export interface InfantryVisualConfig {',
    '  soldiers: readonly [InfantrySoldierVisualConfig, InfantrySoldierVisualConfig, InfantrySoldierVisualConfig];',
    '}',
    '',
    'const INFANTRY_VISUAL_CONFIG: Record<InfantryVisualKind, InfantryVisualConfig> = {',
  ];
  for (const kind of KINDS) {
    const r = byKind.get(kind);
    lines.push(`  ${kind}: { soldiers: [`);
    for (let i = 1; i <= 3; i++) lines.push(`    { spritePath: ${JSON.stringify(r[`sprite${i}Path`])}, scale: ${r[`sprite${i}Scale`]} },`);
    lines.push('  ] },');
  }
  lines.push('};', '', '');
  lines.push('export function infantryVisualKindOf(kind: UnitKind): InfantryVisualKind {');
  lines.push("  return kind === 'german_infantry' || kind === 'soviet_infantry' || kind === 'japanese_infantry' || kind === 'american_infantry' ? kind : 'infantry';");
  lines.push('}', '', 'export function infantryVisualConfigOf(kind: UnitKind): InfantryVisualConfig {');
  lines.push('  return INFANTRY_VISUAL_CONFIG[infantryVisualKindOf(kind)];');
  lines.push('}', '');
  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[buildInfantryVisualDB] OK ${records.length} rows -> ${path.relative(ROOT, OUT_PATH)}`);
}

try { build(); } catch (error) { console.error('[buildInfantryVisualDB] failed:', error.message); process.exit(1); }
