/**
 * Attack direction rules - generated automatically. Do not edit this file by hand.
 *
 * Source: data/attack_direction_table.csv
 * Regenerate: node tools/buildAttackDirectionDB.js
 */

export type ArmorFace = 'front' | 'frontSide' | 'rearSide' | 'rear';
export type DamageCheckType = 'front' | 'right' | 'left' | 'rear';

export interface AttackDirectionRule {
  position: string;
  incomingAngle: number;
  armorFace: ArmorFace;
  damageCheckType: DamageCheckType;
  notes: string;
}

export const ATTACK_DIRECTION_RULES: Record<number, AttackDirectionRule> = {
  [-150]: { position: "正后", incomingAngle: -150, armorFace: 'rear', damageCheckType: 'rear', notes: "左后30度" },
  [-120]: { position: "左后", incomingAngle: -120, armorFace: 'rearSide', damageCheckType: 'right', notes: "左后" },
  [-90]: { position: "正左", incomingAngle: -90, armorFace: 'rearSide', damageCheckType: 'left', notes: "正左" },
  [-60]: { position: "左前", incomingAngle: -60, armorFace: 'frontSide', damageCheckType: 'left', notes: "左前侧" },
  [-30]: { position: "正前", incomingAngle: -30, armorFace: 'front', damageCheckType: 'front', notes: "左前30度" },
  [0]: { position: "正前", incomingAngle: 0, armorFace: 'front', damageCheckType: 'front', notes: "正前" },
  [30]: { position: "正前", incomingAngle: 30, armorFace: 'front', damageCheckType: 'front', notes: "右前30度" },
  [60]: { position: "右前", incomingAngle: 60, armorFace: 'frontSide', damageCheckType: 'right', notes: "右前侧" },
  [90]: { position: "正右", incomingAngle: 90, armorFace: 'frontSide', damageCheckType: 'right', notes: "正右" },
  [120]: { position: "右后", incomingAngle: 120, armorFace: 'rearSide', damageCheckType: 'left', notes: "右后" },
  [150]: { position: "正后", incomingAngle: 150, armorFace: 'rear', damageCheckType: 'rear', notes: "右后30度" },
  [180]: { position: "正后", incomingAngle: 180, armorFace: 'rear', damageCheckType: 'rear', notes: "正后" },
};
