/**
 * Campaign upgrade DB - generated automatically. Do not edit this file by hand.
 *
 * Source: data/campaign_upgrades.csv
 * Regenerate: node tools/buildCampaignUpgradeDB.js
 */

export type CampaignUpgradeId = "commander_cupola" | "improved_optics" | "wet_ammo_rack" | "spall_liner" | "automatic_extinguisher" | "side_skirts" | "wide_tracks" | "improved_transmission" | "smoke_launcher" | "intercom";

export interface CampaignUpgradeDefinition {
  id: CampaignUpgradeId;
  nameKey: string;
  descriptionKey: string;
  interiorVisionBonus: number;
  gunnerVisionBonus: number;
  hitThresholdModifier: number;
  armorFrontSideBonus: number;
  armorRearSideBonus: number;
  mudAttackDiceBonus: number;
  mudMovementDiceBonus: number;
  mudMiscDiceBonus: number;
  miscDiceBonus: number;
  ignoreDestroyed: boolean;
  ignoreCrewCheck: boolean;
  repairDiceCanFireSuppress: boolean;
  driveDiceCanTurn: boolean;
  unlocksSmoke: boolean;
}

export const CAMPAIGN_UPGRADES: readonly CampaignUpgradeDefinition[] = [
  {
    id: "commander_cupola",
    nameKey: "campaignUpgrade.commanderCupola.name",
    descriptionKey: "campaignUpgrade.commanderCupola.description",
    interiorVisionBonus: 1,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "improved_optics",
    nameKey: "campaignUpgrade.improvedOptics.name",
    descriptionKey: "campaignUpgrade.improvedOptics.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 1,
    hitThresholdModifier: -1,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "wet_ammo_rack",
    nameKey: "campaignUpgrade.wetAmmoRack.name",
    descriptionKey: "campaignUpgrade.wetAmmoRack.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: true,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "spall_liner",
    nameKey: "campaignUpgrade.spallLiner.name",
    descriptionKey: "campaignUpgrade.spallLiner.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: true,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "automatic_extinguisher",
    nameKey: "campaignUpgrade.automaticExtinguisher.name",
    descriptionKey: "campaignUpgrade.automaticExtinguisher.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: true,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "side_skirts",
    nameKey: "campaignUpgrade.sideSkirts.name",
    descriptionKey: "campaignUpgrade.sideSkirts.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 1,
    armorRearSideBonus: 1,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "wide_tracks",
    nameKey: "campaignUpgrade.wideTracks.name",
    descriptionKey: "campaignUpgrade.wideTracks.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 1,
    mudMovementDiceBonus: 1,
    mudMiscDiceBonus: 1,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
  {
    id: "improved_transmission",
    nameKey: "campaignUpgrade.improvedTransmission.name",
    descriptionKey: "campaignUpgrade.improvedTransmission.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: true,
    unlocksSmoke: false,
  },
  {
    id: "smoke_launcher",
    nameKey: "campaignUpgrade.smokeLauncher.name",
    descriptionKey: "campaignUpgrade.smokeLauncher.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 0,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: true,
  },
  {
    id: "intercom",
    nameKey: "campaignUpgrade.intercom.name",
    descriptionKey: "campaignUpgrade.intercom.description",
    interiorVisionBonus: 0,
    gunnerVisionBonus: 0,
    hitThresholdModifier: 0,
    armorFrontSideBonus: 0,
    armorRearSideBonus: 0,
    mudAttackDiceBonus: 0,
    mudMovementDiceBonus: 0,
    mudMiscDiceBonus: 0,
    miscDiceBonus: 1,
    ignoreDestroyed: false,
    ignoreCrewCheck: false,
    repairDiceCanFireSuppress: false,
    driveDiceCanTurn: false,
    unlocksSmoke: false,
  },
];

export const CAMPAIGN_UPGRADE_BY_ID = CAMPAIGN_UPGRADES.reduce((out, def) => {
  out[def.id] = def;
  return out;
}, {} as Record<CampaignUpgradeId, CampaignUpgradeDefinition>);
