/**
 * Damage table DB - generated automatically. Do not edit this file by hand.
 *
 * Source: data/damage_table.csv
 * Regenerate: node tools/buildDamageTableDB.js
 */

import type { DamageCheckType } from './AttackDirectionDB';

export type DamageTargetClass = 'german_tank' | 'us_tank' | 'protagonist';
export type DamageTableEffectKind = 'destroyed' | 'fire' | 'turret' | 'paralyzed' | 'radio' | 'crew';
export type DamageTableCrewRole = 'commander' | 'loader' | 'gunner' | 'driver' | 'coDriver';

export interface DamageTableEffect {
  kind: DamageTableEffectKind;
  crew?: DamageTableCrewRole[];
}

export interface DamageTableEntry {
  targetClass: DamageTargetClass;
  damageCheckType: DamageCheckType;
  die: number;
  groups: DamageTableEffect[][];
  notes: string;
}

export const DAMAGE_TABLE: Record<DamageTargetClass, Record<DamageCheckType, Record<number, DamageTableEntry>>> = {
  german_tank: {
    front: {
      1: { targetClass: 'german_tank', damageCheckType: 'front', die: 1, groups: [[{"kind":"fire"}]], notes: "" },
      2: { targetClass: 'german_tank', damageCheckType: 'front', die: 2, groups: [[{"kind":"fire"},{"kind":"crew","crew":["coDriver","driver"]}]], notes: "" },
      3: { targetClass: 'german_tank', damageCheckType: 'front', die: 3, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      4: { targetClass: 'german_tank', damageCheckType: 'front', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'german_tank', damageCheckType: 'front', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'german_tank', damageCheckType: 'front', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    right: {
      1: { targetClass: 'german_tank', damageCheckType: 'right', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["loader","commander"]}]], notes: "" },
      2: { targetClass: 'german_tank', damageCheckType: 'right', die: 2, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      3: { targetClass: 'german_tank', damageCheckType: 'right', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'german_tank', damageCheckType: 'right', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'german_tank', damageCheckType: 'right', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'german_tank', damageCheckType: 'right', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    left: {
      1: { targetClass: 'german_tank', damageCheckType: 'left', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["gunner","commander"]}]], notes: "" },
      2: { targetClass: 'german_tank', damageCheckType: 'left', die: 2, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      3: { targetClass: 'german_tank', damageCheckType: 'left', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'german_tank', damageCheckType: 'left', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'german_tank', damageCheckType: 'left', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'german_tank', damageCheckType: 'left', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    rear: {
      1: { targetClass: 'german_tank', damageCheckType: 'rear', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["commander"]}]], notes: "" },
      2: { targetClass: 'german_tank', damageCheckType: 'rear', die: 2, groups: [[{"kind":"fire"},{"kind":"radio"}]], notes: "" },
      3: { targetClass: 'german_tank', damageCheckType: 'rear', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'german_tank', damageCheckType: 'rear', die: 4, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      5: { targetClass: 'german_tank', damageCheckType: 'rear', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'german_tank', damageCheckType: 'rear', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
  },
  us_tank: {
    front: {
      1: { targetClass: 'us_tank', damageCheckType: 'front', die: 1, groups: [[{"kind":"fire"}]], notes: "" },
      2: { targetClass: 'us_tank', damageCheckType: 'front', die: 2, groups: [[{"kind":"fire"},{"kind":"crew","crew":["coDriver","driver"]}]], notes: "" },
      3: { targetClass: 'us_tank', damageCheckType: 'front', die: 3, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      4: { targetClass: 'us_tank', damageCheckType: 'front', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'us_tank', damageCheckType: 'front', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'us_tank', damageCheckType: 'front', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    right: {
      1: { targetClass: 'us_tank', damageCheckType: 'right', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["gunner","commander"]}]], notes: "" },
      2: { targetClass: 'us_tank', damageCheckType: 'right', die: 2, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      3: { targetClass: 'us_tank', damageCheckType: 'right', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'us_tank', damageCheckType: 'right', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'us_tank', damageCheckType: 'right', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'us_tank', damageCheckType: 'right', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    left: {
      1: { targetClass: 'us_tank', damageCheckType: 'left', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["loader","commander"]}]], notes: "" },
      2: { targetClass: 'us_tank', damageCheckType: 'left', die: 2, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      3: { targetClass: 'us_tank', damageCheckType: 'left', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'us_tank', damageCheckType: 'left', die: 4, groups: [[{"kind":"fire"},{"kind":"turret"}]], notes: "" },
      5: { targetClass: 'us_tank', damageCheckType: 'left', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'us_tank', damageCheckType: 'left', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
    rear: {
      1: { targetClass: 'us_tank', damageCheckType: 'rear', die: 1, groups: [[{"kind":"fire"},{"kind":"crew","crew":["commander"]}]], notes: "" },
      2: { targetClass: 'us_tank', damageCheckType: 'rear', die: 2, groups: [[{"kind":"fire"},{"kind":"radio"}]], notes: "" },
      3: { targetClass: 'us_tank', damageCheckType: 'rear', die: 3, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      4: { targetClass: 'us_tank', damageCheckType: 'rear', die: 4, groups: [[{"kind":"fire"},{"kind":"paralyzed"}]], notes: "" },
      5: { targetClass: 'us_tank', damageCheckType: 'rear', die: 5, groups: [[{"kind":"destroyed"}]], notes: "" },
      6: { targetClass: 'us_tank', damageCheckType: 'rear', die: 6, groups: [[{"kind":"destroyed"}]], notes: "" },
    },
  },
  protagonist: {
    front: {
      1: { targetClass: 'protagonist', damageCheckType: 'front', die: 1, groups: [[{"kind":"destroyed"}]], notes: "" },
      2: { targetClass: 'protagonist', damageCheckType: 'front', die: 2, groups: [[{"kind":"fire"}]], notes: "" },
      3: { targetClass: 'protagonist', damageCheckType: 'front', die: 3, groups: [[{"kind":"fire"}]], notes: "" },
      4: { targetClass: 'protagonist', damageCheckType: 'front', die: 4, groups: [[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      5: { targetClass: 'protagonist', damageCheckType: 'front', die: 5, groups: [[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      6: { targetClass: 'protagonist', damageCheckType: 'front', die: 6, groups: [[{"kind":"crew","crew":["coDriver","driver"]}],[{"kind":"fire"}]], notes: "" },
    },
    right: {
      1: { targetClass: 'protagonist', damageCheckType: 'right', die: 1, groups: [[{"kind":"destroyed"}]], notes: "" },
      2: { targetClass: 'protagonist', damageCheckType: 'right', die: 2, groups: [[{"kind":"fire"}]], notes: "" },
      3: { targetClass: 'protagonist', damageCheckType: 'right', die: 3, groups: [[{"kind":"fire"}]], notes: "" },
      4: { targetClass: 'protagonist', damageCheckType: 'right', die: 4, groups: [[{"kind":"paralyzed"}],[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      5: { targetClass: 'protagonist', damageCheckType: 'right', die: 5, groups: [[{"kind":"paralyzed"}],[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      6: { targetClass: 'protagonist', damageCheckType: 'right', die: 6, groups: [[{"kind":"crew","crew":["gunner","driver","commander"]}],[{"kind":"fire"}]], notes: "" },
    },
    left: {
      1: { targetClass: 'protagonist', damageCheckType: 'left', die: 1, groups: [[{"kind":"destroyed"}]], notes: "" },
      2: { targetClass: 'protagonist', damageCheckType: 'left', die: 2, groups: [[{"kind":"fire"}]], notes: "" },
      3: { targetClass: 'protagonist', damageCheckType: 'left', die: 3, groups: [[{"kind":"fire"}]], notes: "" },
      4: { targetClass: 'protagonist', damageCheckType: 'left', die: 4, groups: [[{"kind":"paralyzed"}],[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      5: { targetClass: 'protagonist', damageCheckType: 'left', die: 5, groups: [[{"kind":"paralyzed"}],[{"kind":"turret"}],[{"kind":"fire"}]], notes: "" },
      6: { targetClass: 'protagonist', damageCheckType: 'left', die: 6, groups: [[{"kind":"crew","crew":["loader","coDriver","commander"]}],[{"kind":"fire"}]], notes: "" },
    },
    rear: {
      1: { targetClass: 'protagonist', damageCheckType: 'rear', die: 1, groups: [[{"kind":"destroyed"}]], notes: "" },
      2: { targetClass: 'protagonist', damageCheckType: 'rear', die: 2, groups: [[{"kind":"fire"}]], notes: "" },
      3: { targetClass: 'protagonist', damageCheckType: 'rear', die: 3, groups: [[{"kind":"fire"}]], notes: "" },
      4: { targetClass: 'protagonist', damageCheckType: 'rear', die: 4, groups: [[{"kind":"radio"}],[{"kind":"paralyzed"}],[{"kind":"fire"}]], notes: "" },
      5: { targetClass: 'protagonist', damageCheckType: 'rear', die: 5, groups: [[{"kind":"paralyzed"}],[{"kind":"radio"}],[{"kind":"fire"}]], notes: "" },
      6: { targetClass: 'protagonist', damageCheckType: 'rear', die: 6, groups: [[{"kind":"crew","crew":["commander"]}],[{"kind":"fire"}]], notes: "" },
    },
  },
};
