/**
 * Fire check DB - generated automatically. Do not edit this file by hand.
 *
 * Source: data/fire_check_table.csv
 * Regenerate: node tools/buildFireCheckDB.js
 */

export type FireCheckProfile = "classic_europe" | "classic_pacific" | "hardcore";
export type FireCheckEffect = "destroyed" | "crewCheck" | "fire" | "turret" | "paralyzed" | "none";

export interface FireCheckEntry {
  profile: FireCheckProfile;
  die: number;
  effect: FireCheckEffect;
  notes: string;
}

export const FIRE_CHECK_TABLE: Record<FireCheckProfile, Record<number, FireCheckEntry>> = {
  classic_europe: {
    1: { profile: 'classic_europe', die: 1, effect: 'destroyed', notes: "" },
    2: { profile: 'classic_europe', die: 2, effect: 'crewCheck', notes: "" },
    3: { profile: 'classic_europe', die: 3, effect: 'fire', notes: "" },
    4: { profile: 'classic_europe', die: 4, effect: 'fire', notes: "" },
    5: { profile: 'classic_europe', die: 5, effect: 'turret', notes: "" },
    6: { profile: 'classic_europe', die: 6, effect: 'paralyzed', notes: "" },
  },
  classic_pacific: {
    1: { profile: 'classic_pacific', die: 1, effect: 'destroyed', notes: "" },
    2: { profile: 'classic_pacific', die: 2, effect: 'crewCheck', notes: "" },
    3: { profile: 'classic_pacific', die: 3, effect: 'fire', notes: "" },
    4: { profile: 'classic_pacific', die: 4, effect: 'turret', notes: "" },
    5: { profile: 'classic_pacific', die: 5, effect: 'paralyzed', notes: "" },
    6: { profile: 'classic_pacific', die: 6, effect: 'none', notes: "" },
  },
  hardcore: {
    1: { profile: 'hardcore', die: 1, effect: 'destroyed', notes: "" },
    2: { profile: 'hardcore', die: 2, effect: 'crewCheck', notes: "" },
    3: { profile: 'hardcore', die: 3, effect: 'fire', notes: "" },
    4: { profile: 'hardcore', die: 4, effect: 'turret', notes: "" },
    5: { profile: 'hardcore', die: 5, effect: 'paralyzed', notes: "" },
    6: { profile: 'hardcore', die: 6, effect: 'none', notes: "" },
  },
};
