/**
 * Infantry squad presentation database. Auto-generated; do not edit this file.
 *
 * Source: data/infantry_visuals.csv
 * Rebuild: node tools/buildInfantryVisualDB.js
 */

import { UnitKind } from './types';

export type InfantryVisualKind = Extract<UnitKind, 'infantry' | 'german_infantry' | 'soviet_infantry' | 'japanese_infantry' | 'american_infantry'>;
export const INFANTRY_VISUAL_KINDS: readonly InfantryVisualKind[] = ['infantry', 'german_infantry', 'soviet_infantry', 'japanese_infantry', 'american_infantry'];

export interface InfantrySoldierVisualConfig {
  spritePath: string;
  scale: number;
}

export interface InfantryVisualConfig {
  soldiers: readonly [InfantrySoldierVisualConfig, InfantrySoldierVisualConfig, InfantrySoldierVisualConfig];
}

const INFANTRY_VISUAL_CONFIG: Record<InfantryVisualKind, InfantryVisualConfig> = {
  infantry: { soldiers: [
    { spritePath: "textures/units/Infantry01/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry02/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry03/spriteFrame", scale: 0.69 },
  ] },
  german_infantry: { soldiers: [
    { spritePath: "textures/units/Infantry01/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry02/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry03/spriteFrame", scale: 0.69 },
  ] },
  soviet_infantry: { soldiers: [
    { spritePath: "textures/units/Infantry01/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry02/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/Infantry03/spriteFrame", scale: 0.6 },
  ] },
  japanese_infantry: { soldiers: [
    { spritePath: "textures/units/JapaneseInfantry01/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/JapaneseInfantry02/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/JapaneseInfantry03/spriteFrame", scale: 0.6 },
  ] },
  american_infantry: { soldiers: [
    { spritePath: "textures/units/AmericanInfantry01/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/AmericanInfantry02/spriteFrame", scale: 0.6 },
    { spritePath: "textures/units/AmericanInfantry03/spriteFrame", scale: 0.6 },
  ] },
};


export function infantryVisualKindOf(kind: UnitKind): InfantryVisualKind {
  return kind === 'german_infantry' || kind === 'soviet_infantry' || kind === 'japanese_infantry' || kind === 'american_infantry' ? kind : 'infantry';
}

export function infantryVisualConfigOf(kind: UnitKind): InfantryVisualConfig {
  return INFANTRY_VISUAL_CONFIG[infantryVisualKindOf(kind)];
}
