/**
 * 本地化文案 —— 自动生成，请勿手改本文件。
 *
 * 数据源：data/lang.csv
 * 重新生成：node tools/buildLangDB.js
 */

export interface LangEntry {
  zh: string;
  en: string;
}

export const LANG_DB: Record<string, LangEntry> = {
  'dmg.effect.destroyed': { zh: "摧毁", en: "Destroyed" },
  'dmg.effect.damaged': { zh: "受损", en: "Damaged" },
  'dmg.effect.fire': { zh: "起火 +1", en: "On Fire +1" },
  'dmg.effect.turret': { zh: "炮塔受损", en: "Turret Hit" },
  'dmg.effect.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'dmg.effect.crewCheck': { zh: "阵亡检定", en: "Crew Check" },
  'dmg.effect.radio': { zh: "无线电损坏", en: "Radio Hit" },
  'dmg.outcome.destroyed': { zh: "击毁", en: "Destroyed" },
  'dmg.outcome.damaged': { zh: "受损", en: "Damaged" },
  'dmg.outcome.fire': { zh: "起火", en: "On Fire" },
  'dmg.outcome.turret': { zh: "炮塔受损", en: "Turret Hit" },
  'dmg.outcome.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'dmg.outcome.crewCheck': { zh: "阵亡检定", en: "Crew Check" },
  'dmg.outcome.radio': { zh: "无线电损坏", en: "Radio Hit" },
  'turnEnd.result.noEffect': { zh: "无事发生", en: "No effect" },
  'crew.role.1': { zh: "车长", en: "Commander" },
  'crew.role.2': { zh: "装填手", en: "Loader" },
  'crew.role.3': { zh: "炮手", en: "Gunner" },
  'crew.role.4': { zh: "驾驶员", en: "Driver" },
  'crew.role.5': { zh: "副驾驶", en: "Co-driver" },
  'crew.death.falseAlarmHatch': { zh: "虚惊（舱盖关）", en: "False Alarm (Hatch Closed)" },
  'crew.death.falseAlarm': { zh: "乘员虚惊", en: "Crew False Alarm" },
  'crew.death.kia': { zh: "{role} 阵亡", en: "{role} KIA" },
  'unit.status.destroyed': { zh: "已毁", en: "Destroyed" },
  'unit.status.fire': { zh: "起火", en: "On Fire" },
  'hud.init': { zh: "回合 - | 行动力 -/-", en: "Turn - | AP -/-" },
  'hud.missionLine': { zh: "{id} · {name}", en: "{id} — {name}" },
  'hud.enemyTurn': { zh: "回合 {n} | 敌方行动中...", en: "Turn {n} | Enemy acting..." },
  'hud.playerChoose': { zh: "回合 {n} | 玩家 | 选择阶段 · {tags}", en: "Turn {n} | Player | Choose phase · {tags}" },
  'hud.movePhase': { zh: "回合 {n} | 移动阶段 | 骰子 {dice}", en: "Turn {n} | Move phase | Dice {dice}" },
  'hud.attackPhase': { zh: "回合 {n} | 攻击阶段 | {loaded} | 骰子 {dice}{sel}", en: "Turn {n} | Attack phase | {loaded} | Dice {dice}{sel}" },
  'hud.attackSelectHint': { zh: "点敌人开火", en: "Click enemy to fire" },
  'hud.precisionAttackSelectHint': { zh: "精确射击：点敌人开火", en: "Precision fire: click enemy" },
  'hud.mgSelectHint': { zh: "点步兵扫射", en: "Click infantry" },
  'hud.loaded': { zh: "已装填", en: "Loaded" },
  'hud.unloaded': { zh: "未装填", en: "Unloaded" },
  'hud.moveDone': { zh: "✓移动", en: "✓Move" },
  'hud.moveTodo': { zh: "·移动", en: "·Move" },
  'hud.attackDone': { zh: "✓攻击", en: "✓Attack" },
  'hud.attackTodo': { zh: "·攻击", en: "·Attack" },
  'hud.miscDone': { zh: "✓杂项", en: "✓Misc" },
  'hud.miscTodo': { zh: "·杂项", en: "·Misc" },
  'hud.miscPhase': { zh: "回合 {n} | 杂项阶段 | 骰子 {dice}", en: "Turn {n} | Misc phase | Dice {dice}" },
  'btn.nextPhase': { zh: "下一阶段", en: "Next Phase" },
  'btn.endTurn': { zh: "结束回合", en: "End Turn" },
  'btn.enemyTurnRunning': { zh: "敌方回合中", en: "Enemy Turn" },
  'btn.save': { zh: "存档", en: "Save" },
  'btn.load': { zh: "读档", en: "Load" },
  'btn.restart': { zh: "再来一局", en: "Play Again" },
  'btn.backToMenu': { zh: "返回主菜单", en: "Back to Menu" },
  'btn.movePhase': { zh: "移动阶段", en: "Move Phase" },
  'btn.attackPhase': { zh: "攻击阶段", en: "Attack Phase" },
  'btn.miscPhase': { zh: "杂项阶段", en: "Misc Phase" },
  'btn.hatchOpen': { zh: "打开舱盖", en: "Open hatch" },
  'btn.hatchClose': { zh: "关闭舱盖", en: "Close hatch" },
  'btn.hatchCommanderKia': { zh: "车长阵亡", en: "Commander KIA" },
  'outcome.win': { zh: "胜利！", en: "Victory!" },
  'outcome.lose': { zh: "战败", en: "Defeat" },
  'objective.prefix': { zh: "任务目标{n}：", en: "Objective {n}: " },
  'objective.destroyProgress.tank': { zh: "击毁{unit} {cur}/{total}", en: "Destroy {unit} {cur}/{total}" },
  'objective.destroyProgress.officer': { zh: "击杀{unit} {cur}/{total}", en: "Kill {unit} {cur}/{total}" },
  'objective.destroyProgress.infantry': { zh: "消灭{unit} {cur}/{total}", en: "Eliminate {unit} {cur}/{total}" },
  'objective.destroyAllProgress': { zh: "击毁所有单位，剩余{remaining}", en: "Destroy all units, remaining {remaining}" },
  'objective.destroyAllRemaining': { zh: "击毁所有单位，剩余{remaining}", en: "Destroy all units, remaining {remaining}" },
  'objective.destroyAllUnitsRemaining': { zh: "击毁所有单位，剩余{remaining}", en: "Destroy all units, remaining {remaining}" },
  'objective.destroyTruckProgress': { zh: "击毁卡车 {cur}/{total}", en: "Destroy trucks {cur}/{total}" },
  'objective.usCasualties': { zh: "美军伤亡 {cur}/{limit}", en: "US casualties {cur}/{limit}" },
  'objective.evacFromMark': { zh: "从指定位置撤离", en: "Evacuate from the marked hex" },
  'objective.exitEdge': { zh: "从地图边缘指定方向离境", en: "Leave the map at the designated edge" },
  'objective.typeUnknown': { zh: "任务目标（{type}）", en: "Objective ({type})" },
  'status.panelTitle': { zh: "谢尔曼状态", en: "Sherman Status" },
  'status.row.loaded': { zh: "装填", en: "Loaded" },
  'status.row.hatch': { zh: "舱盖", en: "Hatch" },
  'status.row.fire': { zh: "车体", en: "Hull" },
  'status.row.turret': { zh: "炮塔", en: "Turret" },
  'status.row.mobility': { zh: "机动", en: "Mobility" },
  'status.row.fireLevel': { zh: "着火程度", en: "Fire level" },
  'status.row.crewTitle': { zh: "乘员", en: "Crew" },
  'status.crew.1': { zh: "① 车长", en: "① COM" },
  'status.crew.2': { zh: "② 装填手", en: "② LDR" },
  'status.crew.3': { zh: "③ 炮手", en: "③ GUN" },
  'status.crew.4': { zh: "④ 驾驶员", en: "④ DRV" },
  'status.crew.5': { zh: "⑤ 副驾驶", en: "⑤ ASD" },
  'status.val.loaded': { zh: "已装填", en: "Loaded" },
  'status.val.unloaded': { zh: "未装填", en: "Unloaded" },
  'status.val.hatchOpen': { zh: "打开舱盖", en: "PU" },
  'status.val.hatchClosed': { zh: "关闭舱盖", en: "BU" },
  'status.val.destroyed': { zh: "已毁", en: "Destroyed" },
  'status.val.fireN': { zh: "起火({n})", en: "Fire({n})" },
  'status.val.damaged': { zh: "受损", en: "Damaged" },
  'status.val.intact': { zh: "完好", en: "Intact" },
  'status.val.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'status.val.normal': { zh: "正常", en: "Normal" },
  'status.val.crewDead': { zh: "阵亡", en: "KIA" },
  'status.val.crewAlive': { zh: "存活", en: "Alive" },
  'dice.tray.move': { zh: "移动阶段骰子（点骰子选择动作）", en: "Move Phase Dice (tap a die to act)" },
  'dice.tray.attack': { zh: "攻击阶段骰子（点骰子选择动作）", en: "Attack Phase Dice (tap a die to act)" },
  'dice.tray.misc': { zh: "杂项阶段骰子（点骰子选择动作）", en: "Misc Phase Dice (tap a die to act)" },
  'dice.slot.used': { zh: "已用", en: "Used" },
  'die.hint.turn': { zh: "转向", en: "Turn" },
  'die.hint.drive': { zh: "前进", en: "Advance" },
  'die.hint.reverse': { zh: "后退", en: "Reverse" },
  'die.hint.start': { zh: "启动", en: "Start" },
  'floater.hatchLocked': { zh: "本回合舱盖已锁定", en: "Hatch locked this turn" },
  'floater.hatchCommanderDead': { zh: "车长已阵亡，操作无效", en: "Commander is dead; action invalid" },
  'floater.hatchAlreadyClosed': { zh: "舱盖已经关闭", en: "Hatch is already closed" },
  'floater.hatchClosedByDice': { zh: "舱盖已关闭", en: "Hatch closed" },
  'die.hint.reload': { zh: "装填", en: "Reload" },
  'die.hint.gun': { zh: "主炮", en: "Gun" },
  'die.hint.mg': { zh: "机枪", en: "MG" },
  'die.hint.repair': { zh: "修复", en: "Repair" },
  'die.hint.fireSuppress': { zh: "灭火", en: "Put Out Fire" },
  'die.hint.smoke': { zh: "烟雾", en: "Sm" },
  'die.hint.conceal': { zh: "隐蔽", en: "Conceal" },
  'die.hint.gunOrLoad': { zh: "炮/填", en: "Gun/Load" },
  'die.hint.driverTurnOrDrive': { zh: "驾:转/进", en: "Driver:Turn/Advance" },
  'die.hint.smokeOrRepair': { zh: "烟/修", en: "Sm/Re" },
  'die.hint.codriverMG': { zh: "副机枪", en: "Co-MG" },
  'die.hint.none': { zh: "—", en: "—" },
  'action.turnCW': { zh: "↻ 顺时针 60°", en: "↻ CW 60°" },
  'action.turnCCW': { zh: "↺ 逆时针 60°", en: "↺ CCW 60°" },
  'action.advance': { zh: "▲ 前进 1 格", en: "▲ Advance 1" },
  'action.reverse': { zh: "▼ 后退 1 格", en: "▼ Reverse 1" },
  'action.reload': { zh: "装填主炮", en: "Reload Gun" },
  'action.repair': { zh: "修复", en: "Repair" },
  'action.fire': { zh: "炮击", en: "Fire" },
  'action.fireHardcore': { zh: "炮击/旋转", en: "Fire/Rotate" },
  'action.repairTurret': { zh: "修复炮塔", en: "Repair Turret" },
  'action.repairMobility': { zh: "修复瘫痪", en: "Repair Mobility" },
  'action.fireSuppress': { zh: "灭火 -1", en: "Reduce Fire -1" },
  'action.smoke': { zh: "施放烟雾", en: "Deploy Smoke" },
  'action.concealment': { zh: "进入隐蔽", en: "Go Concealed" },
  'action.codriverMG': { zh: "副驾驶机枪", en: "Co-driver MG" },
  'action.fireMG': { zh: "机枪扫射", en: "Fire MG" },
  'action.fireMGCoDriver': { zh: "副驾驶机枪扫射", en: "Co-driver Fire MG" },
  'floater.noFacing': { zh: "未定朝向", en: "No Facing" },
  'floater.blockedTerrain': { zh: "地形阻挡", en: "Blocked Terrain" },
  'floater.enemyBlock': { zh: "敌方占据", en: "Enemy Blocks" },
  'floater.smoke': { zh: "烟雾", en: "Smoke" },
  'floater.repair': { zh: "修复", en: "Repair" },
  'floater.repairAndFire': { zh: "修复并灭火", en: "Repair/Fire" },
  'floater.noRepair': { zh: "无需修复", en: "Nothing to Repair" },
  'floater.noFire': { zh: "无起火", en: "No Fire" },
  'floater.alreadyLoaded': { zh: "主炮已装填，无需再次装填", en: "Main gun already loaded" },
  'floater.alreadySmoked': { zh: "已处于烟雾中", en: "Already in smoke" },
  'floater.alreadyConcealed': { zh: "已处于隐蔽中", en: "Already concealed" },
  'floater.notImplemented': { zh: "暂未实装", en: "Not Yet Implemented" },
  'floater.noInfantry': { zh: "无可射击步兵", en: "No Valid Infantry" },
  'floater.noGunTarget': { zh: "无可射击的主炮目标", en: "No Valid Main Gun Target" },
  'floater.fireReduced': { zh: "起火程度 -1", en: "Fire Level -1" },
  'floater.turretFixed': { zh: "炮塔已修复", en: "Turret Repaired" },
  'floater.mobilityFixed': { zh: "机动已修复", en: "Mobility Repaired" },
  'floater.paralyzedBlocked': { zh: "瘫痪中无法移动", en: "Immobilized: Cannot Move" },
  'floater.beachNoSmoke': { zh: "在海里无法使用烟雾", en: "Cannot use smoke in the water" },
  'floater.beachNoRepair': { zh: "在海里无法使用修复", en: "Cannot repair in the water" },
  'floater.beachNoConceal': { zh: "在海里无法使用隐蔽", en: "Cannot conceal in the water" },
  'floater.smokeDeployed': { zh: "施放烟雾", en: "Smoke Deployed" },
  'floater.concealed': { zh: "进入隐蔽", en: "Concealed" },
  'floater.revealed': { zh: "暴露（离开隐蔽）", en: "Revealed" },
  'floater.needPair': { zh: "需要两颗同点骰", en: "Need Pair of Dice" },
  'floater.smokeCleared': { zh: "烟雾消散", en: "Smoke Cleared" },
  'floater.fireCheck': { zh: "着火检定", en: "Fire Check" },
  'floater.mgMiss': { zh: "机枪未命中", en: "MG Miss" },
  'floater.mgHit': { zh: "步兵击毙", en: "Infantry Down" },
  'floater.mgDice': { zh: "机枪 1d6={sum}", en: "MG 1d6={sum}" },
  'floater.roleUnavailable': { zh: "{role}已阵亡，无法操作", en: "{role} KIA: cannot act" },
  'action.concealPair': { zh: "隐蔽（+同点骰）", en: "Go Concealed (+pair)" },
  'action.doublesDriverAdvance': { zh: "前进（+同点骰）", en: "Driver Advance (+pair)" },
  'action.doublesCoDriverTurnCW': { zh: " ↻ 60°（+同点骰）", en: "Co-driver ↻ 60° (+pair)" },
  'action.doublesCoDriverTurnCCW': { zh: " ↺ 60°（+同点骰）", en: "Co-driver ↺ 60° (+pair)" },
  'action.doublesLoaderReload': { zh: "装填（+同点骰）", en: "Loader Reload (+pair)" },
  'action.doublesGunnerFire': { zh: "主炮射击（+同点骰）", en: "Gunner Fire (+pair)" },
  'action.precisionFire': { zh: "精确射击（命中所需 -2）", en: "Precision Fire (hit need -2)" },
  'action.closeHatchPair': { zh: "关闭舱盖（+同点骰）", en: "Close Hatch (+pair)" },
  'attack.reason.selfFire': { zh: "不能攻击自己", en: "Cannot Target Self" },
  'attack.reason.destroyedTarget': { zh: "目标已被摧毁", en: "Target Destroyed" },
  'attack.reason.overlap': { zh: "目标重叠", en: "Overlap" },
  'attack.reason.notStraight': { zh: "非六向直线", en: "Not on Hex Axis" },
  'attack.reason.notStraightHint': { zh: "射击死角", en: "Must be on hex axis" },
  'attack.reason.cannotTurnDirection': { zh: "不能转向该方向", en: "Cannot turn in that direction" },
  'attack.reason.turretAimRange': { zh: "超出当前视野范围", en: "Beyond current vision range" },
  'attack.reason.fixedGunFacing': { zh: "固定炮只能沿当前朝向开火", en: "Fixed gun can only fire forward" },
  'attack.reason.blocked': { zh: "无视线", en: "No LOS" },
  'attack.reason.turretDamaged': { zh: "炮塔受损不能开火", en: "Turret Damaged: Cannot Fire" },
  'attack.reason.mgRange': { zh: "机枪目标距离不合法", en: "MG: Invalid Target Range" },
  'attack.reason.notInfantry': { zh: "机枪只能扫射步兵", en: "MG: Target Must Be Infantry" },
  'attack.reason.gunVsInfantry': { zh: "主炮不瞄步兵，请改用机枪", en: "Main gun ignores infantry; use MG" },
  'attack.reason.unknown': { zh: "无法攻击", en: "Cannot Attack" },
  'preview.impossible': { zh: "≥{n}\\n几乎不可能", en: "≥{n}\\nImpossible" },
  'dice.panel.hitNeed': { zh: "命中需 ≥{n}", en: "Hit ≥{n}" },
  'dice.panel.mgHitNeed': { zh: "机枪扫射 命中需 ≥{n}", en: "MG Burst · Hit ≥{n}" },
  'dice.panel.outcomeMGKill': { zh: "步兵击毙", en: "Infantry Down" },
  'dice.panel.hitYes': { zh: "命中", en: "Hit" },
  'dice.panel.hitNo': { zh: "未命中", en: "Miss" },
  'dice.panel.hitDoublesCommanderKia': { zh: "命中骰对子：车长阵亡", en: "Hit doubles: Commander KIA" },
  'dice.panel.penMustPen': { zh: "必穿 (≤0)", en: "Auto-Pen (≤0)" },
  'dice.panel.penNeed': { zh: "需 ≥{n}", en: "Need ≥{n}" },
  'dice.panel.penYes': { zh: "击穿", en: "Penetrate" },
  'dice.panel.penNo': { zh: "跳弹", en: "Ricochet" },
  'dice.panel.invalid': { zh: "无效", en: "Invalid" },
  'dice.panel.dmgTitle': { zh: "伤害检定", en: "Damage Check" },
  'dice.panel.crewTitle': { zh: "阵亡检定", en: "Crew Check" },
  'dice.panel.outcomeMiss': { zh: "MISS", en: "MISS" },
  'dice.panel.outcomeRic': { zh: "跳弹", en: "Ricochet" },
  'dice.panel.outcomeCommanderKia': { zh: "车长阵亡！", en: "Commander KIA!" },
  'actor.player': { zh: "玩家", en: "Player" },
  'actor.sherman': { zh: "谢尔曼", en: "Sherman" },
  'actor.enemyPrefix': { zh: "敌方 {name}", en: "Enemy {name}" },
  'actor.allyPrefix': { zh: "友军 {name}", en: "Allied {name}" },
  'unit.name.sherman': { zh: "谢尔曼", en: "Sherman" },
  'unit.name.tiger': { zh: "虎式", en: "Tiger" },
  'unit.name.panzer4': { zh: "四号", en: "Panzer IV" },
  'unit.name.panzer3': { zh: "三号", en: "Panzer III" },
  'unit.name.truck': { zh: "卡车", en: "Truck" },
  'unit.name.infantry': { zh: "步兵", en: "Infantry" },
  'unit.name.officer': { zh: "军官", en: "Officer" },
  'unit.name.type95': { zh: "九五式", en: "Type 95 Ha-Go" },
  'unit.name.type97': { zh: "九七式", en: "Type 97 Chi-Ha" },
  'unit.name.at_gun': { zh: "反坦克炮", en: "AT Gun" },
  'unit.name.japanese_infantry': { zh: "日本步兵", en: "Japanese Infantry" },
  'unit.name.heavy_artillery': { zh: "重炮", en: "Heavy Artillery" },
  'terrain.clear': { zh: "开阔地", en: "Clear" },
  'terrain.trees': { zh: "树木", en: "Trees" },
  'terrain.beach': { zh: "海滩", en: "Beach" },
  'terrain.rocky': { zh: "岩石高地", en: "Rocky high ground" },
  'terrain.deep_water': { zh: "深海", en: "Deep sea" },
  'terrain.airstrip': { zh: "机场", en: "Airstrip" },
  'dice.aiHeader': { zh: "{col}  {n}骰", en: "{col}  {n}d" },
  'dice.aiHeader.hardcoreTank': { zh: "{terrain} 攻击{attack}/移动{move}", en: "{terrain} Attack {attack}/Move {move}" },
  'dice.aiTerrain.road': { zh: "公路", en: "Road" },
  'dice.aiTerrain.field': { zh: "田地", en: "Field" },
  'dice.aiTerrain.mud': { zh: "泥地", en: "Mud" },
  'dice.aiTerrain.clear': { zh: "沙地", en: "Sand" },
  'dice.aiTerrain.trees': { zh: "树木", en: "Trees" },
  'dice.aiTerrain.beach': { zh: "海滩", en: "Beach" },
  'dice.aiTerrain.airstrip': { zh: "机场", en: "Airstrip" },
  'dice.aiCol.road': { zh: "公路", en: "Road" },
  'dice.aiCol.field': { zh: "田野", en: "Field" },
  'dice.aiCol.mud': { zh: "泥地", en: "Mud" },
  'dice.aiCol.damaged': { zh: "受损", en: "Damaged" },
  'dice.aiCol.type95': { zh: "九五式", en: "Type 95" },
  'dice.aiCol.type97': { zh: "九七式", en: "Type 97" },
  'dice.aiCol.at_gun': { zh: "反坦克炮", en: "AT Gun" },
  'dice.aiCol.japanese_infantry': { zh: "日本步兵", en: "Japanese Infantry" },
  'dice.aiCol.heavy_artillery': { zh: "重炮", en: "Heavy Artillery" },
  'dice.aiEnemy.shoot': { zh: "主炮射击", en: "Main gun" },
  'dice.aiEnemy.turn': { zh: "转向", en: "Turn" },
  'dice.aiEnemy.advance': { zh: "前进", en: "Advance" },
  'dice.aiEnemy.reverse': { zh: "后退", en: "Reverse" },
  'dice.aiEnemy.smoke': { zh: "烟雾", en: "Smoke" },
  'dice.aiEnemy.repair': { zh: "修复并灭火", en: "Repair/Fire" },
  'dice.aiEnemy.conceal': { zh: "隐蔽", en: "Conceal" },
  'dice.aiEnemy.shoot_adjacent': { zh: "相邻射击", en: "Adjacent fire" },
  'dice.aiEnemy.infantry_move': { zh: "步兵移动", en: "Infantry move" },
  'dice.aiEnemy.advance_to_building': { zh: "进入建筑", en: "Enter building" },
  'dice.aiEnemy.hull_down': { zh: "Hull Down", en: "Hull Down" },
  'dice.aiEnemy.none': { zh: "无", en: "None" },
  'dice.aiEnemy.waste': { zh: "空转", en: "No action" },
  'menu.title': { zh: "孤胆谢尔曼", en: "Lone Sherman" },
  'menu.subtitle': { zh: "LONE SHERMAN · 1944", en: "LONE SHERMAN · 1944" },
  'menu.continue': { zh: "继续游戏", en: "Continue" },
  'menu.noSave': { zh: "无存档", en: "No Save" },
  'menu.continueSummary': { zh: "回合 {turn} · {phase} · {mission}", en: "Turn {turn} · {phase} · {mission}" },
  'menu.mode.title': { zh: "游戏模式", en: "GAME MODE" },
  'menu.mode.classic': { zh: "经典", en: "Classic" },
  'menu.mode.hardcore': { zh: "硬核", en: "Hardcore" },
  'menu.phase.player': { zh: "玩家阶段", en: "Player Phase" },
  'menu.phase.enemy': { zh: "敌方阶段", en: "Enemy Phase" },
  'chapter.europe.title': { zh: "欧洲战场", en: "European Theater" },
  'chapter.europe.subtitle': { zh: "第一章节 · 12 个任务", en: "Chapter I · 12 missions" },
  'chapter.pacific.title': { zh: "太平洋战场", en: "Pacific Theater" },
  'chapter.pacific.subtitle': { zh: "第二章节 · 12 个任务", en: "Chapter II · 12 missions" },
  'level.pacific.01.title': { zh: "塔拉瓦，红滩 1 - 登陆鸟嘴", en: "Tarawa, Red Beach 1 - Landing at the Bird's Beak" },
  'level.pacific.02.title': { zh: "塔拉瓦红滩 1：向内陆推进", en: "Tarawa - Red Beach 1: Pushing Inland" },
  'level.pacific.03.title': { zh: "塔拉瓦，红滩 1 - 清理机场西侧", en: "Tarawa, Red Beach 1 - Clear the West of the Airfield" },
  'level.pacific.04.title': { zh: "塞班岛登陆", en: "Saipan - The Landing" },
  'level.pacific.05.title': { zh: "塞班岛 - 向北前往加拉潘", en: "Saipan - North towards Garapan" },
  'level.pacific.06.title': { zh: "塞班岛 - 清理加拉潘", en: "Saipan - Clearing Garapan" },
  'level.pacific.07.title': { zh: "塔拉瓦，红滩 2 - 登陆", en: "Tarawa, Red Beach 2 - The Landing" },
  'level.pacific.08.title': { zh: "塔拉瓦，红滩 2 - 清理中央机场", en: "Tarawa, Red Beach 2 - Clear the Central Airfield" },
  'level.pacific.09.title': { zh: "塔拉瓦，红滩 2 - 清理机场东侧", en: "Tarawa, Red Beach 2 - Clear the East of the Airfield" },
  'level.pacific.10.title': { zh: "贝里琉 - 登陆", en: "Peleliu - The Landing" },
  'level.pacific.11.title': { zh: "贝里琉坦克冲锋", en: "Peleliu - Japanese Tank Charge" },
  'level.pacific.12.title': { zh: "贝里琉 - 清理机场", en: "Peleliu - Clear the Airfield" },
  'chapter.test.title': { zh: "测试关卡", en: "Test Missions" },
  'chapter.test.subtitle': { zh: "调试与验证用任务", en: "Debug and validation missions" },
  'chapter.custom.title': { zh: "我的关卡", en: "My Missions" },
  'chapter.custom.subtitle': { zh: "关卡编辑器与本地自定义关卡（最多 10 个）", en: "Level editor and local custom missions (up to 10)" },
  'chapter.empty.title': { zh: "战区待命", en: "Theater Standby" },
  'chapter.empty.body': { zh: "本章节任务正在准备中，后续新增关卡会自动出现在这里。", en: "Missions for this chapter are in preparation. New levels will appear here automatically." },
  'menu.selectMission': { zh: "选 择 任 务", en: "Select Mission" },
  'menu.locked': { zh: "未解锁", en: "Locked" },
  'menu.notReady': { zh: "关卡未开放", en: "Level Not Ready" },
  'menu.version': { zh: "v0.1.0 · build {b}", en: "v0.1.0 · build {b}" },
  'menu.settings.title': { zh: "设置", en: "Settings" },
  'menu.settings.bgmVolume': { zh: "背景音乐", en: "Music" },
  'menu.settings.sfxVolume': { zh: "音效", en: "Sound FX" },
  'menu.settings.lang': { zh: "语言", en: "Language" },
  'menu.settings.langZh': { zh: "中文", en: "Chinese" },
  'menu.settings.langEn': { zh: "English", en: "English" },
  'menu.settings.close': { zh: "关闭", en: "Close" },
  'menu.help.title': { zh: "游戏说明", en: "How to Play" },
  'menu.help.body': { zh: "· 目标：操控谢尔曼完成每关任务要求。\\n\\n· 每回合行动阶段由攻击/移动/杂项3个阶段组成，攻击和移动可自由选择先后顺序，每个阶段根据所在地形获得对应数量的行动骰子。\\n\\n· 移动阶段：使用对应点数转向、前进、后退，两个相同骰子可以合并执行新的动作。\\n\\n· 攻击阶段：主炮需要装填后才可使用，可攻击直线上未被视线阻挡的装甲单位；机枪可扫射直线上未被视线阻挡的步兵（1D6 命中检定）。\\n\\n· 杂项阶段：装填、灭火、隐蔽、烟雾、副驾驶机枪等。\\n\\n· 敌方回合：按距离由近到远依次行动；步兵只在回合结束事件里出没。\\n\\n· 操作：点骰子弹出动作菜单；选中对应选项后执行动作。", en: "· Goal: Complete each mission's objectives with the Sherman.\\n\\n· Each turn has three action phases (Attack / Move / Misc). Attack and Move may be resolved in either order; each phase grants action dice according to the terrain you occupy.\\n\\n· Move phase: spend matching pips to turn, advance, or reverse; two identical dice may be merged to perform new actions.\\n\\n· Attack phase: the main gun can only be used after loading; it may fire at armored targets along a straight line if line of sight is clear. The machine gun may strafe infantry along a clear straight line (roll 1d6 to hit).\\n\\n· Misc phase: reload, extinguish fire, concealment, smoke, co-driver MG, and more.\\n\\n· Enemy phase: enemies act from nearest to farthest; enemy infantry only appear during end-of-turn events.\\n\\n· Controls: tap a die to open its action menu; pick an option to execute it." },
  'menu.help.gotIt': { zh: "已 了 解", en: "Got it" },
  'menu.modal.close': { zh: "✕", en: "✕" },
  'level.01.title': { zh: "村庄", en: "Village" },
  'level.02.title': { zh: "猎杀虎式", en: "Hunt the Tiger" },
  'level.03.title': { zh: "清除步兵", en: "Clear Infantry" },
  'level.04.title': { zh: "只是路过：湖泊", en: "Just Passing Through: Lake" },
  'level.05.title': { zh: "摧毁卡车", en: "Destroy Truck" },
  'level.06.title': { zh: "以一敌三", en: "One Against Three" },
  'level.07.title': { zh: "只是路过：桥梁", en: "Just Passing Through: Bridge" },
  'level.08.title': { zh: "刺杀", en: "Assassination" },
  'level.09.title': { zh: "跨过水域", en: "Crossing the Water" },
  'level.10.title': { zh: "只是路过：城镇", en: "Just Passing Through: Town" },
  'level.11.title': { zh: "钢铁角斗士", en: "Steel Gladiator" },
  'level.12.title': { zh: "猎杀虎式Ⅱ", en: "Hunt the Tiger II" },
  'level.test.title': { zh: "测试关卡", en: "Test Mission" },
  'level.custom.editor.title': { zh: "关卡编辑器", en: "Level Editor" },
  'level.custom.mission.title': { zh: "自定义关卡", en: "Custom Mission" },
  'levelEditor.placeholder.body': { zh: "关卡编辑器入口已创建，编辑器功能正在接入中。当前不会再进入无响应的测试场景。下一步将实现地图、单位、目标和事件编辑界面。", en: "The level editor entry is ready, and the editor UI is being connected. It will no longer open the unresponsive test scene. Next up: map, unit, objective, and event editing." },
  'levelEditor.placeholder.back': { zh: "返回我的关卡", en: "Back to My Missions" },
  'levelEditor.workspace.hint': { zh: "选择左侧地形，然后点击六边形格子刷地形。", en: "Choose terrain on the left, then click hex cells to paint." },
  'levelEditor.workspace.terrain': { zh: "地形", en: "Terrain" },
  'levelEditor.terrain.none': { zh: "无", en: "None" },
  'levelEditor.workspace.current': { zh: "当前编辑：{name}", en: "Editing: {name}" },
  'levelEditor.workspace.newDraft': { zh: "新关卡草稿", en: "New Mission Draft" },
  'levelEditor.workspace.new': { zh: "新建关卡", en: "New Mission" },
  'levelEditor.workspace.newReady': { zh: "已切换到新关卡草稿，保存后会创建一个新的本地关卡。", en: "Switched to a new draft. Save it to create a new local mission." },
  'levelEditor.workspace.prev': { zh: "上一关卡", en: "Prev" },
  'levelEditor.workspace.next': { zh: "下一关卡", en: "Next" },
  'levelEditor.workspace.noSaved': { zh: "还没有已保存的自定义关卡。", en: "No saved custom missions yet." },
  'levelEditor.workspace.save': { zh: "保存到我的关卡", en: "Save to My Missions" },
  'levelEditor.workspace.saved': { zh: "已保存到当前关卡。关闭面板后可在“我的关卡”中试玩。", en: "Saved to the current mission. Close this panel to play it from My Missions." },
  'levelEditor.workspace.savedNew': { zh: "已创建新关卡。后续保存会覆盖这个关卡。", en: "Created a new mission. Future saves will overwrite this mission." },
  'levelEditor.workspace.saveFull': { zh: "保存失败：自定义关卡已达上限（最多 10 个）。", en: "Save failed: custom mission limit reached (up to 10)." },
  'levelEditor.workspace.delete': { zh: "删除当前关卡", en: "Delete Current" },
  'levelEditor.workspace.deleted': { zh: "当前关卡已删除，已切换到新关卡草稿。", en: "Deleted the current mission and switched to a new draft." },
  'levelEditor.workspace.deleteUnsaved': { zh: "当前是新草稿，尚未保存，无需删除。", en: "This is an unsaved draft, so there is nothing to delete." },
  'terrain.road': { zh: "公路", en: "Road" },
  'terrain.field': { zh: "田野", en: "Field" },
  'terrain.mud': { zh: "泥地", en: "Mud" },
  'terrain.forest': { zh: "森林", en: "Forest" },
  'terrain.water': { zh: "水域", en: "Water" },
  'tileInspect.title': { zh: "格子介绍", en: "Tile info" },
  'tileInspect.building': { zh: "建筑叠加：坦克可进入格内；视线沿路径经过建筑格时会被遮挡。", en: "Building overlay: tanks may enter the tile; line of sight is blocked when the sight path passes through a building tile." },
  'tileInspect.rules.forest': { zh: "森林：谢尔曼与德军坦克不可进入；步兵可进入；遮挡视线。", en: "Forest: Sherman and German tanks cannot enter; infantry can enter; blocks line of sight." },
  'tileInspect.rules.water': { zh: "水域：任何单位不可进入；不遮挡视线。", en: "Water: impassable to all units; does not block line of sight." },
  'tileInspect.hedges': { zh: "主炮射击时视线上的每个树篱使命中所需点数+1，但攻击者相邻的树篱不增加命中所需点数。", en: "For main-gun fire, each hedge along the line of sight adds +1 to the hit number, but hedges adjacent to the attacker do not increase the hit number." },
  'tileInspect.breakwaters': { zh: "防波堤：日军单位移动不受影响；盟军坦克在移动阶段不能跨越，仅杂项阶段 3 点的前进动作可跨越。", en: "Breakwater: Japanese units ignore it. Allied tanks cannot cross it during the Move phase; only the Misc-phase 3-pip advance may cross." },
  'tileInspect.markerRid': { zh: "援军标记 rid={n}", en: "Reinforcement marker rid={n}" },
  'tileInspect.markerEid': { zh: "敌军出生点标记 eid={n}", en: "Enemy start marker eid={n}" },
  'tileInspect.diceIntro': { zh: "掷骰规则：各地形在移动 / 攻击 / 杂项子阶段的基础颗数见下；再叠加乘员与舱盖修正后，总颗数下限为 {capMin}，不设最大上限。", en: "Dice: per-terrain base counts for movement / attack / misc below; crew and hatch modifiers apply; total dice have a minimum of {capMin} and no maximum cap." },
  'tileInspect.diceRow.move': { zh: "移动阶段：基础骰子 {n} 颗，驾驶员存活 +{md}、副驾驶存活 +{mc}、车长开舱 +{mh}。", en: "Movement: base {n} dice; driver alive +{md}, co-driver alive +{mc}, commander hatch open +{mh}." },
  'tileInspect.diceRow.moveHardcore': { zh: "移动阶段：基础骰子 {n} 颗，驾驶员存活 +{md}、副驾驶存活 +{mc}、车长存活 +{mh}。", en: "Movement: base {n} dice; driver alive +{md}, co-driver alive +{mc}, commander alive +{mh}." },
  'tileInspect.diceRow.attack': { zh: "攻击阶段：基础骰子 {n} 颗，炮手存活 +{ag}、装填手存活 +{al}、车长开舱 +{ah}。", en: "Attack: base {n} dice; gunner alive +{ag}, loader alive +{al}, commander hatch open +{ah}." },
  'tileInspect.diceRow.attackHardcore': { zh: "攻击阶段：基础骰子 {n} 颗，炮手存活 +{ag}、装填手存活 +{al}、车长存活 +{ah}。", en: "Attack: base {n} dice; gunner alive +{ag}, loader alive +{al}, commander alive +{ah}." },
  'tileInspect.diceRow.misc': { zh: "杂项阶段：基础骰子 {n} 颗，车长开舱 +{xc}。", en: "Misc: base {n} dice; commander hatch open +{xc}." },
  'tileInspect.unitBlock': { zh: "{name}\\n状态：{status}", en: "{name}\\nStatus: {status}" },
  'tileInspect.currentUnit': { zh: "当前单位：{name}", en: "Current unit: {name}" },
  'tileInspect.currentStatus': { zh: "当前状态：{status}", en: "Current status: {status}" },
  'tileInspect.infantryNoTable': { zh: "该单位不套用装甲 / 穿甲数据表。", en: "This unit has no armor / penetration stat table." },
  'tileInspect.colFront': { zh: "前装甲", en: "Front" },
  'tileInspect.colFrontSide': { zh: "前侧装甲", en: "Front side" },
  'tileInspect.colRearSide': { zh: "后侧装甲", en: "Rear side" },
  'tileInspect.colRear': { zh: "后装甲", en: "Rear" },
  'tileInspect.colPen': { zh: "穿甲值", en: "Pen." },
  'tileInspect.colEffectiveRange': { zh: "有效射程", en: "Eff. range" },
  'tileInspect.effectiveRange': { zh: "有效射程：{n}", en: "Effective range: {n}" },
  'tileInspect.statusNone': { zh: "无额外状态", en: "No extra status" },
  'tileInspect.noUnit': { zh: "当前格上无单位。", en: "No unit on this tile." },
  'tileInspect.unitUnknown': { zh: "当前格单位状态未知", en: "Unit status on this tile is currently unknown." },
  'tileInspect.statusSep': { zh: "；", en: "; " },
  'tileInspect.status.shermanFire': { zh: "着火 {n} 级", en: "Fire level {n}" },
  'tileInspect.status.turretDamaged': { zh: "炮塔受损", en: "Turret damaged" },
  'tileInspect.status.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'tileInspect.status.radioDamaged': { zh: "无线电损坏", en: "Radio damaged" },
  'tileInspect.status.hidden': { zh: "隐蔽", en: "Concealed" },
  'tileInspect.status.smoked': { zh: "烟雾", en: "Smoked" },
  'tileInspect.status.loaded': { zh: "主炮已装填", en: "Main gun loaded" },
  'tileInspect.status.unloaded': { zh: "主炮未装填", en: "Main gun not loaded" },
  'tileInspect.status.hatchOpen': { zh: "舱盖打开", en: "Hatches open" },
  'tileInspect.status.enemyDamaged': { zh: "车体受损", en: "Hull damaged" },
  'battleLog.title': { zh: "战斗记录 · 点标题放大", en: "Combat log · tap title to expand" },
  'battleLog.ready': { zh: "[系统] 战斗记录就绪。", en: "[System] Combat log ready." },
  'battleLog.missionLoaded': { zh: "[战斗] 任务加载成功：{name}，{tiles} 格，1 + {allies} + {enemies} 个单位", en: "[Battle] Mission loaded: {name}, {tiles} tiles, 1 + {allies} + {enemies} units" },
  'battleLog.playerTurnStart': { zh: "[战斗] === 进入回合 {turn}（玩家）===", en: "[Battle] === Enter turn {turn} (Player) ===" },
  'battleLog.hatch': { zh: "[舱盖] 车长舱盖 -> {state}", en: "[Hatch] Commander hatch -> {state}" },
  'battleLog.phase.movement': { zh: "移动", en: "Move" },
  'battleLog.phase.attack': { zh: "攻击", en: "Attack" },
  'battleLog.phase.misc': { zh: "杂项", en: "Misc" },
  'battleLog.diceRoll': { zh: "[骰子] {phase}阶段掷骰：[{dice}]（{count} 颗，地形 {terrain}，舱盖 {hatch}）", en: "[Dice] {phase} phase roll: [{dice}] ({count} dice, terrain {terrain}, hatch {hatch})" },
  'battleLog.diceAutoEnd': { zh: "[骰子] {phase}阶段骰子用尽，自动结束阶段", en: "[Dice] {phase} phase dice exhausted; auto-ending phase" },
  'battleLog.outcome.victory': { zh: "胜利", en: "Victory" },
  'battleLog.outcome.defeat': { zh: "战败", en: "Defeat" },
  'battleLog.outcome.ongoing': { zh: "进行中", en: "Ongoing" },
  'battleLog.unitArrived': { zh: "[战斗] {unit} 到达（q={q}, r={r}）", en: "[Battle] {unit} arrived (q={q}, r={r})" },
  'battleLog.unitTurnDone': { zh: "[战斗] {unit} 转向完成，朝向={facing}", en: "[Battle] {unit} finished turning, facing={facing}" },
  'battleLog.unitEvacuated': { zh: "[战斗] {unit} 撤离完成 -> {outcome}", en: "[Battle] {unit} evacuated -> {outcome}" },
  'battleLog.truckExitDefeat': { zh: "[战斗] 卡车驶离公路终点 -> {outcome}", en: "[Battle] Truck exited the road end -> {outcome}" },
  'battleLog.usCasualtyCheck': { zh: "[Pacific] 美军伤亡检定：骰 {dice}，6点 {hits} 个，累计 {cur}/{limit}", en: "[Pacific] US casualty check: dice {dice}; sixes {hits}; total {cur}/{limit}" },
  'battleLog.usCasualtyDefeat': { zh: "[Pacific] 美军伤亡 {cur}/{limit}，超过上限，任务失败", en: "[Pacific] US casualties {cur}/{limit}; limit exceeded; mission failed" },
  'battleLog.move.turn': { zh: "[移动] 转向 {dir} -> 朝向={facing}（动画中）", en: "[Move] Turn {dir} -> facing={facing} (animating)" },
  'battleLog.move.drive': { zh: "[移动] {action} -> ({q},{r})", en: "[Move] {action} -> ({q},{r})" },
  'battleLog.move.evacuate': { zh: "[移动] 撤离离场 -> ({q},{r})（目标格无地形）", en: "[Move] Evacuate off-map -> ({q},{r}) (no terrain)" },
  'battleLog.move.doublesDrive': { zh: "[移动] 对子：驾驶员前进 -> ({q},{r})（消耗两颗骰）", en: "[Move] Pair: driver advance -> ({q},{r}) (spend two dice)" },
  'battleLog.move.doublesEvacuate': { zh: "[移动] 对子：驾驶员撤离离场 -> ({q},{r})", en: "[Move] Pair: driver evacuates off-map -> ({q},{r})" },
  'battleLog.move.doublesTurn': { zh: "[移动] 对子：副驾驶转向 {dir} -> 朝向={facing}（动画中）", en: "[Move] Pair: co-driver turn {dir} -> facing={facing} (animating)" },
  'battleLog.attack.reload': { zh: "[攻击] 装填完成", en: "[Attack] Reload complete" },
  'battleLog.attack.doublesReload': { zh: "[攻击] 对子：装填手装填完成（消耗两颗骰）", en: "[Attack] Pair: loader reload complete (spend two dice)" },
  'battleLog.attack.doublesGunReady': { zh: "[攻击] 对子：炮手主炮射击已备（主骰 {dieIdx} + 搭档 {partnerIdx}，点数 {pip}）", en: "[Attack] Pair: gunner main-gun shot ready (die {dieIdx} + partner {partnerIdx}, pip {pip})" },
  'battleLog.attack.precisionReady': { zh: "[攻击] 精确射击已备（同点骰 {pip}，命中所需 -2）", en: "[Attack] Precision fire ready (matching pip {pip}, hit need -2)" },
  'battleLog.attack.precisionAI': { zh: "[AI] {actor}消耗同点骰 {pip} 执行精确射击，修正后命中所需 ≥{need}", en: "[AI] {actor} consumes matching pip {pip} for precision fire; modified hit need ≥{need}" },
  'battleLog.misc.repairTurret': { zh: "[杂项] 修复炮塔", en: "[Misc] Turret repaired" },
  'battleLog.misc.repairMobility': { zh: "[杂项] 修复瘫痪", en: "[Misc] Mobility repaired" },
  'battleLog.misc.fireSuppress': { zh: "[杂项] 灭火 -> 着火层数 {from} -> {to}", en: "[Misc] Fire suppression -> fire level {from} -> {to}" },
  'battleLog.misc.smoke': { zh: "[杂项] 施放烟雾 -> 当前格产生烟雾", en: "[Misc] Smoke deployed -> current hex smoked" },
  'battleLog.misc.conceal': { zh: "[杂项] 进入隐蔽（消耗骰 {dieIdx} + {partnerIdx}，点数 {pip}）", en: "[Misc] Concealed (spent dice {dieIdx} + {partnerIdx}, pip {pip})" },
  'battleLog.side.ally': { zh: "友军阶段", en: "Allied phase" },
  'battleLog.side.german': { zh: "德军阶段", en: "German phase" },
  'battleLog.phaseSide': { zh: "[战斗] === 回合 {turn} {side}开始（{count} 个单位）===", en: "[Battle] === Turn {turn} {side} begins ({count} units) ===" },
  'battleLog.armorFace.front': { zh: "正面", en: "front" },
  'battleLog.armorFace.frontSide': { zh: "前侧", en: "front side" },
  'battleLog.armorFace.rearSide': { zh: "后侧", en: "rear side" },
  'battleLog.armorFace.rear': { zh: "后方", en: "rear" },
  'battleLog.combat.miss': { zh: "[战斗] {actor} 2d6={d1}+{d2}={roll}，需要 {need} -> 未命中", en: "[Combat] {actor} 2d6={d1}+{d2}={roll}, needs {need} -> miss" },
  'battleLog.combat.hitDoublesCommanderKia': { zh: "[战斗] {actor} 命中骰掷出对子 {d1}+{d2}，谢尔曼舱盖打开 -> 车长阵亡", en: "[Combat] {actor} hit dice doubles {d1}+{d2}; Sherman hatch open -> Commander KIA" },
  'battleLog.combat.cannotAttack': { zh: "[战斗] 无法攻击：{reason}", en: "[Combat] Cannot attack: {reason}" },
  'battleLog.combatMg': { zh: "[战斗] 玩家机枪命中骰={diceExpr}，需要 ≥{need} -> {result}", en: "[Combat] Player MG hit dice={diceExpr}; needs ≥{need} -> {result}" },
  'battleLog.combatMgAI': { zh: "[战斗] {actor}主炮无目标，改用机枪：命中骰={diceExpr}，需要 ≥{need} -> {result}", en: "[Combat] {actor} has no main-gun target and uses MG: hit dice={diceExpr}; needs ≥{need} -> {result}" },
  'battleLog.combatMg.hit': { zh: "命中击毙", en: "Hit and killed" },
  'battleLog.combatMg.miss': { zh: "未命中", en: "Miss" },
  'battleLog.combat.ricochet': { zh: "[战斗] {actor} 2d6={d1}+{d2}={roll}，需要 {need} -> 命中{face}（装甲 {armor} / 穿甲 {pen}），穿甲骰={penDiceExpr}，需要 {penNeed} -> 跳弹", en: "[Combat] {actor} 2d6={d1}+{d2}={roll}, needs {need} -> hit {face} (armor {armor} / pen {pen}), AP dice={penDiceExpr}, needs {penNeed} -> ricochet" },
  'battleLog.combat.directDestroy': { zh: "[战斗] {actor} 2d6={d1}+{d2}={roll}，需要 {need} -> 命中{face}（装甲 {armor} / 穿甲 {pen}），穿甲骰={penDiceExpr}，需要 {penNeed} -> 击穿，目标摧毁", en: "[Combat] {actor} 2d6={d1}+{d2}={roll}, needs {need} -> hit {face} (armor {armor} / pen {pen}), AP dice={penDiceExpr}, needs {penNeed} -> penetrated, target destroyed" },
  'battleLog.combat.damage': { zh: "[战斗] {actor} 2d6={d1}+{d2}={roll}，需要 {need} -> 命中{face}（装甲 {armor} / 穿甲 {pen}），穿甲骰={penDiceExpr}，需要 {penNeed} -> 击穿 -> 伤害骰 1d6={dmgDie} -> {effect} -> {target}", en: "[Combat] {actor} 2d6={d1}+{d2}={roll}, needs {need} -> hit {face} (armor {armor} / pen {pen}), AP dice={penDiceExpr}, needs {penNeed} -> penetrated -> damage 1d6={dmgDie} -> {effect} -> {target}" },
  'battleLog.unknown': { zh: "未知", en: "unknown" },
  'battle.settings.title': { zh: "战斗设置", en: "Battle Settings" },
  'battle.settings.exit': { zh: "退出关卡", en: "Exit Level" },
  'battle.turnEndList.title': { zh: "回合结束事件（本关）", en: "Turn-end events (this mission)" },
  'battle.turnEndList.empty': { zh: "本关未配置回合结束事件表。", en: "This mission has no turn-end event table." },
  'battle.turnEndList.line': { zh: "{range}（主骰 {n} 颗，点数之和）→ {effect}", en: "{range} (sum of {n} dice) → {effect}" },
  'battle.turnEndList.effect.none': { zh: "本回合没有事件发生", en: "No event occurs this turn" },
  'battle.turnEndList.effect.sniper': { zh: "狙击手", en: "Sniper" },
  'battle.turnEndList.effect.commander_extra': { zh: "车长额外指挥", en: "Commander bonus" },
  'battle.turnEndList.effect.infantry_spawn': { zh: "德军步兵增援", en: "German infantry reinforcement" },
  'battle.turnEndList.effect.japanese_infantry_spawn': { zh: "日军步兵增援", en: "Japanese infantry reinforcement" },
  'battle.turnEndList.effect.adjacent_infantry_fire': { zh: "相邻步兵齐射", en: "Adjacent infantry volley" },
  'battle.turnEndList.effect.mechanical_failure': { zh: "机械故障", en: "Mechanical failure" },
  'battle.turnEndList.effect.stuka': { zh: "斯图卡空袭", en: "Stuka raid" },
  'battle.turnEndList.effect.panzer3_spawn': { zh: "III 号坦克增援", en: "Panzer III reinforcement" },
  'battle.turnEndList.effect.road_mine': { zh: "公路地雷（谢尔曼在公路上）", en: "Road mine (Sherman on road)" },
  'battle.turnEndList.effect.panzer4_spawn': { zh: "IV 号坦克增援", en: "Panzer IV reinforcement" },
  'battle.turnEndList.effect.tiger_spawn': { zh: "虎式坦克增援", en: "Tiger reinforcement" },
  'battle.turnEndList.effect.sherman_spawn': { zh: "谢尔曼增援", en: "Sherman reinforcement" },
  'battle.turnEndList.effect.german_truck_move': { zh: "德军卡车沿路推进", en: "German truck advances on road" },
  'battle.turnEndList.effect.clear_mine': { zh: "开阔地地雷", en: "Clear-hex mine" },
  'battle.turnEndList.effect.type95_spawn': { zh: "九五式增援", en: "Type 95 reinforcement" },
  'battle.turnEndList.effect.type97_spawn': { zh: "九七式增援", en: "Type 97 reinforcement" },
  'battle.turnEndList.effect.heavy_mortar': { zh: "重迫击炮火力", en: "Heavy mortar fire" },
  'turnEnd.mine.skip': { zh: "地雷：谢尔曼不在公路格，或已瘫痪，未触发。", en: "Mine: not on a road or immobilized; no effect." },
  'turnEnd.mine.ric': { zh: "地雷：命中间隙装甲未击穿（穿甲掷骰 {penDie}）。", en: "Mine: failed to penetrate (AP roll {penDie})." },
  'turnEnd.mine.hit': { zh: "地雷：击穿！伤害掷骰 {damageDie}，最终结果：{result}。", en: "Mine: penetrated! Damage die {damageDie}; final result: {result}." },
  'turnEnd.extra.minePen': { zh: "穿甲 0 vs 装甲 4", en: "Pen. 0 vs AV 4" },
  'turnEnd.extra.mineDmg': { zh: "伤害", en: "Damage" },
  'turnEnd.panzer4.placed': { zh: "敌军 IV 号坦克增援：起始格骰 {spawnDie}，eid={eid}。", en: "Panzer IV reinforcement: start die {spawnDie} eid={eid}." },
  'turnEnd.panzer4.blocked': { zh: "IV 号增援：骰 {spawnDie}，格 eid={eid} 被坦克占据。", en: "Panzer IV: eid {eid} blocked." },
  'turnEnd.tiger.placed': { zh: "敌军虎式坦克增援：起始格骰 {spawnDie}，eid={eid}。", en: "Tiger reinforcement: start die {spawnDie} eid={eid}." },
  'turnEnd.tiger.blocked': { zh: "虎式增援：骰 {spawnDie}，格 eid={eid} 被坦克占据。", en: "Tiger: eid {eid} blocked." },
  'turnEnd.sherman.placed': { zh: "敌军谢尔曼增援：起始格骰 {spawnDie}，eid={eid}。", en: "Sherman reinforcement: start die {spawnDie} eid={eid}." },
  'turnEnd.sherman.blocked': { zh: "谢尔曼增援：骰 {spawnDie}，格 eid={eid} 被坦克占据。", en: "Sherman: eid {eid} blocked." },
  'turnEnd.type97.placed': { zh: "日军九七式增援：起始格骰 {spawnDie}，eid={eid}。格可用则确认后放置。", en: "Type 97 reinforcement: start die {spawnDie} eid={eid}. Confirm to place if clear." },
  'turnEnd.type97.blocked': { zh: "九七式增援：骰 {spawnDie}，目标格 eid={eid} 被占据、不可用或位于岩石高地，未部署。", en: "Type 97 reinforcement: die {spawnDie}; eid={eid} blocked, invalid, or rocky; not placed." },
  'turnEnd.extra.type97Start': { zh: "九七式起始格骰（1d6）", en: "Type 97 start tile (1d6)" },
  'turnEnd.type95.placed': { zh: "日军九五式增援：编号格骰 {spawnDie}。格可用则确认后放置。", en: "Type 95 reinforcement: numbered hex die {spawnDie}. Confirm to place if clear." },
  'turnEnd.type95.blocked': { zh: "九五式增援：骰 {spawnDie}，目标编号格被占据、不可用或位于岩石高地，未部署。", en: "Type 95 reinforcement: die {spawnDie}; numbered hex blocked, invalid, or rocky; not placed." },
  'turnEnd.extra.type95Start': { zh: "九五式起始格骰（1d6）", en: "Type 95 start tile (1d6)" },
  'turnEnd.clearMine.skip': { zh: "地雷：谢尔曼不在开阔地格，或已瘫痪，未触发。", en: "Mine: Sherman is not on a Clear hex or is immobilized; no effect." },
  'turnEnd.clearMine.hit': { zh: "地雷：开阔地自动命中，伤害掷骰 {damageDie}，最终结果：{result}。确认后应用到谢尔曼。", en: "Mine: automatic hit on Clear hex; damage die {damageDie}; final result: {result}. Confirm to apply." },
  'turnEnd.heavyMortar.skip': { zh: "重迫击炮：场上没有与谢尔曼非相邻的日军步兵，未触发。", en: "Heavy mortar: no Japanese infantry is non-adjacent to Sherman; no effect." },
  'turnEnd.heavyMortar.ric': { zh: "重迫击炮：自动命中，击穿骰 {pen1}+{pen2}={penSum}，需要 {penThreshold} -> 未击穿。", en: "Heavy mortar: automatic hit; penetration {pen1}+{pen2}={penSum}, needs {penThreshold} -> no penetration." },
  'turnEnd.heavyMortar.hit': { zh: "重迫击炮：自动命中，击穿骰 {pen1}+{pen2}={penSum}，需要 {penThreshold} -> 击穿；伤害骰 {damageDie}，最终结果：{result}。确认后应用到谢尔曼。", en: "Heavy mortar: automatic hit; penetration {pen1}+{pen2}={penSum}, needs {penThreshold} -> penetrated; damage die {damageDie}; final result: {result}. Confirm to apply." },
  'turnEnd.extra.mortarPen': { zh: "重迫击炮击穿骰（2d6，AV8 / AP0）", en: "Heavy mortar penetration (2d6, AV8 / AP0)" },
  'turnEnd.germanTruck.noConfig': { zh: "本关未配置 truckPath。", en: "This mission has no truckPath." },
  'turnEnd.germanTruck.dead': { zh: "德军卡车已被击毁，本事件不移动卡车。", en: "Truck destroyed; no movement." },
  'turnEnd.germanTruck.lost': { zh: "德军卡车未在 truckPath 上，无法推进。", en: "Truck not on truckPath; cannot advance." },
  'turnEnd.germanTruck.escaped': { zh: "前方沿路格子被坦克占据，本回合卡车无法继续前进（任务仍进行中）。", en: "Tank-occupied hexes block the road ahead; the truck cannot advance this turn (mission continues)." },
  'turnEnd.germanTruck.atRoadEnd': { zh: "德军卡车沿当前朝向单步推进至公路最后一格（任务仍进行中；下一次卡车移动事件触发时将驶离地图、判负）。", en: "German truck advances one hex along its current facing toward the road's edge (mission continues; the next truck-move event will drive it off-map and trigger defeat)." },
  'turnEnd.germanTruck.escapeDrive': { zh: "德军卡车已到达公路末端：将沿当前朝向驶离地图；驶离完成后任务失败（卡车撤离，不计击毁）。", en: "The truck is at the end of the road: it will drive off-map along its current facing. Mission fails when the move completes; the truck withdraws and is not counted as destroyed." },
  'turnEnd.germanTruck.moved': { zh: "德军卡车沿路前进（本次跨越 {stepCells} 格，至路径第 {toIdx} 格）。", en: "German truck advances {stepCells} hex(es) (now at path step {toIdx})." },
  'turnEnd.extra.panzer4Start': { zh: "IV 号起始格骰（1d6）", en: "Panzer IV start tile (1d6)" },
  'turnEnd.extra.tigerStart': { zh: "虎式起始格骰（1d6）", en: "Tiger start tile (1d6)" },
  'turnEnd.extra.shermanStart': { zh: "谢尔曼起始格骰（1d6）", en: "Sherman start tile (1d6)" },
  'battle.save.ok': { zh: "已存档", en: "Game saved" },
  'battle.save.busy': { zh: "忙碌中无法存档", en: "Cannot save while busy" },
  'battle.save.notOngoing': { zh: "胜负已分无法存档", en: "Cannot save after battle ends" },
  'battle.save.playerOnly': { zh: "仅玩家回合可存档", en: "Save only in player turn" },
  'battle.save.fail': { zh: "存档写入失败", en: "Save failed" },
  'battle.load.ok': { zh: "已读档", en: "Game loaded" },
  'battle.load.none': { zh: "无存档", en: "No save data" },
  'battle.load.badJson': { zh: "存档格式损坏", en: "Save data corrupted" },
  'battle.load.busy': { zh: "忙碌中无法读档", en: "Cannot load while busy" },
  'battle.load.fail': { zh: "读档失败：{reason}", en: "Load failed: {reason}" },
  'turnEnd.title': { zh: "回合结束事件", en: "Turn-end event" },
  'turnEnd.confirm': { zh: "确认", en: "OK" },
  'turnEnd.sumLine': { zh: "主骰 {dice}，合计 {sum}", en: "Rolled {dice} (sum {sum})" },
  'turnEnd.none.body': { zh: "事件骰 {d1}+{d2}={sum}。本回合没有事件发生。", en: "Event dice {d1}+{d2}={sum}. No event occurs this turn." },
  'turnEnd.extra.spawnReinforce': { zh: "增援格骰（1d6）", en: "Reinforcement tile (1d6)" },
  'turnEnd.extra.adjacentHit2d6': { zh: "相邻步兵齐射 · 命中判定（2d6）", en: "Adjacent infantry volley · hit (2d6)" },
  'turnEnd.extra.adjacentMg2d6': { zh: "相邻步兵齐射 · 机枪火力（2d6）", en: "Adjacent infantry volley · MG fire (2d6)" },
  'turnEnd.extra.panzer3Start': { zh: "III 号起始格骰（1d6）", en: "Panzer III start tile (1d6)" },
  'turnEnd.extra.stukaAa': { zh: "车长对空射击（2d6）", en: "Commander AA fire (2d6)" },
  'turnEnd.extra.stukaBomb': { zh: "斯图卡轰炸命中判定（2d6≥8；不是伤害）", en: "Stuka bombing hit check (2d6≥8; not damage)" },
  'turnEnd.extra.stukaPen': { zh: "穿甲检定：穿甲 1 vs 装甲 4（1d6≥3）", en: "Penetration: AP 1 vs AV 4 (1d6≥3)" },
  'turnEnd.extra.stukaDamage': { zh: "伤害表（1d6，仅击穿后）", en: "Damage table (1d6 after penetration)" },
  'turnEnd.extra.stukaCrew': { zh: "阵亡检定（1d6）", en: "Crew casualty check (1d6)" },
  'turnEnd.sniper.kia': { zh: "敌方狙击手：谢尔曼舱盖开启且视野内有步兵。事件骰 {d1}+{d2}={sum}。车长中弹阵亡。", en: "Enemy sniper: hatch open with infantry in sight. Event dice {d1}+{d2}={sum}. Commander KIA." },
  'turnEnd.sniper.safe': { zh: "敌方狙击手射击（事件骰 {d1}+{d2}={sum}）。舱盖状态 {hatch}、视野内步兵 {los}，未造成车长伤亡。", en: "Enemy sniper fires (event dice {d1}+{d2}={sum}). Hatch={hatch} LOS infantry={los}; commander unharmed." },
  'turnEnd.commanderExtra.skip': { zh: "车长额外指挥：车长不在位，无效果。", en: "Commander bonus: no commander; no effect." },
  'turnEnd.commanderExtra.fire': { zh: "车长组织灭火：着火层数 -1。", en: "Commander leads firefighting: fire level -1." },
  'turnEnd.commanderExtra.paralyze': { zh: "车长督促抢修：解除瘫痪。", en: "Commander oversees repairs: immobilized cleared." },
  'turnEnd.commanderExtra.turret': { zh: "车长督导炮塔抢修：炮塔恢复可用。", en: "Commander supervises turret repair: turret restored." },
  'turnEnd.commanderExtra.load': { zh: "车长督促装填：主炮完成装填。", en: "Commander urges loading: main gun loaded." },
  'turnEnd.infantry.placed': { zh: "德军步兵增援：增援骰 {spawnDie}，部署至增援格 rid={rid}（若格空）。确认后放置单位。", en: "German infantry reinforcement: die {spawnDie} at reinforce tile rid={rid} if clear. Confirm to place." },
  'turnEnd.infantry.blocked': { zh: "德军步兵增援：增援骰 {spawnDie}，目标格 rid={rid} 不可用或已被占据，未部署。", en: "Infantry reinforcement: die {spawnDie}; tile rid={rid} blocked or occupied; not placed." },
  'turnEnd.japaneseInfantry.placed': { zh: "日军步兵增援：增援骰 {spawnDie}，部署至编号格 rid={rid}（若格空）。确认后放置单位。", en: "Japanese infantry reinforcement: die {spawnDie} at numbered tile rid={rid} if clear. Confirm to place." },
  'turnEnd.japaneseInfantry.blocked': { zh: "日军步兵增援：增援骰 {spawnDie}，目标编号格 rid={rid} 不可用或已被占据，未部署。", en: "Japanese infantry reinforcement: die {spawnDie}; numbered tile rid={rid} blocked or occupied; not placed." },
  'turnEnd.adjacent': { zh: "与谢尔曼相邻的敌军步兵集火：已按直射或间接火力规则结算。", en: "Adjacent enemy infantry fire on the Sherman: resolved per direct/indirect rules." },
  'turnEnd.adjacent.noTarget': { zh: "步兵射程内无攻击目标。", en: "No attack target in infantry range." },
  'turnEnd.mechanical.already': { zh: "机械故障：谢尔曼已瘫痪，无额外效果。", en: "Mechanical failure: already immobilized; no extra effect." },
  'turnEnd.mechanical.ok': { zh: "机械故障：行走/动力受损，谢尔曼瘫痪。", en: "Mechanical failure: Sherman immobilized." },
  'turnEnd.stuka.miss': { zh: "斯图卡空袭：未对谢尔曼造成有效毁伤（详见各掷骰）。", en: "Stuka attack: no effective damage to the Sherman." },
  'turnEnd.stuka.shotDown': { zh: "车长对空射击 2d6={aa1}+{aa2}={aasum}（≥6）：斯图卡被击落，无轰炸命中。", en: "AA fire 2d6={aa1}+{aa2}={aasum} (≥6): Stuka shot down; no bomb hit." },
  'turnEnd.stuka.hit': { zh: "斯图卡轰炸命中车体：轰炸命中 2d6={b1}+{b2}={bsum}；随后按装甲 4 / 穿甲 1 结算穿甲与伤害，最终结果：{result}。确认后应用到谢尔曼。", en: "Stuka bomb hit: hit check 2d6={b1}+{b2}={bsum}; resolve AP 1 vs AV 4 and damage; final result: {result}. Confirm to apply." },
  'turnEnd.stuka.bombMiss': { zh: "斯图卡投弹未命中装甲目标：{b1}+{b2}={bsum}（需≥8）。", en: "Stuka bombs miss armor: {b1}+{b2}={bsum} (need ≥8)." },
  'turnEnd.stuka.ric': { zh: "斯图卡炸弹命中，但按装甲 4 / 穿甲 1 的穿甲骰未过阈值，无车体伤害。", en: "Bomb hit but AP 1 vs AV 4 failed to penetrate; no hull damage." },
  'turnEnd.panzer3.placed': { zh: "敌军 III 号坦克增援：起始格骰 {spawnDie}，eid={eid}。格可用则确认后放置。", en: "Panzer III reinforcement: start die {spawnDie} eid={eid}. Confirm to place if tile free." },
  'turnEnd.panzer3.blocked': { zh: "III 号增援：骰 {spawnDie}，目标格 eid={eid} 被坦克占据或不可用，未部署。", en: "Panzer III reinforcement: die {spawnDie}; tile eid={eid} blocked; not placed." },
  'turnEnd.unknown': { zh: "未配置的回合结束效果类型。", en: "Unknown turn-end effect." },
  'fireCheck.title': { zh: "着火程度检定", en: "Fire intensity check" },
  'fireCheck.confirm': { zh: "确定", en: "OK" },
  'fireCheck.intro': { zh: "按着火层数 {n} 掷 {rolls} 颗 d6：{dice}；取最低 {lowest} 结算一次。", en: "Roll {rolls} fire check d6 for fire level {n}: {dice}; resolve the lowest {lowest} once." },
  'fireCheck.stepLine': { zh: "第{idx}次：d6={die} → {outcome}", en: "Roll {idx}: d6={die} → {outcome}" },
  'fireCheck.lowestLine': { zh: "最低骰：d6={die} → {outcome}", en: "Lowest die: d6={die} → {outcome}" },
  'fireCheck.crewKia': { zh: "阵亡检定 d6={cd}：{role} 阵亡", en: "Crew check d6={cd}: {role} KIA" },
  'fireCheck.crewSafe': { zh: "阵亡检定 d6={cd}：虚惊", en: "Crew check d6={cd}: false alarm" },
  'fireCheck.batchFire': { zh: "本次结果为「起火+1」。最低点结算后着火程度 +{k}。", en: "This result adds fire. Fire level +{k} after resolving the lowest die." },
  'usCasualty.title': { zh: "美军伤亡检定", en: "US Casualty Check" },
  'usCasualty.providers': { zh: "各单位提供的骰子数量：\\n{lines}", en: "Dice provided by units:\\n{lines}" },
  'usCasualty.providerLine': { zh: "{unit}*{units}：{dice}颗", en: "{unit}*{units}: {dice}" },
  'usCasualty.noProviders': { zh: "各单位提供的骰子数量：无", en: "Dice provided by units: none" },
  'usCasualty.noDice': { zh: "无骰子", en: "No dice" },
  'usCasualty.result': { zh: "美军伤亡+{hits}", en: "US Casualties +{hits}" },
  'usCasualty.confirm': { zh: "确定", en: "OK" },
};
