/**
 * 本地化文案 —— 自动生成，请勿手改本文件。
 *
 * 数据源：data/lang.csv
 * 重新生成：node tools/buildLangDB.js
 */

export interface LangEntry {
  zh: string;
  en: string;
}

export const LANG_DB: Record<string, LangEntry> = {
  'dmg.effect.destroyed': { zh: "摧毁！", en: "Destroyed!" },
  'dmg.effect.damaged': { zh: "受损", en: "Damaged" },
  'dmg.effect.fire': { zh: "起火 +1", en: "On Fire +1" },
  'dmg.effect.turret': { zh: "炮塔受损", en: "Turret Hit" },
  'dmg.effect.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'dmg.effect.crewCheck': { zh: "阵亡检定", en: "Crew Check" },
  'dmg.outcome.destroyed': { zh: "击毁", en: "Destroyed" },
  'dmg.outcome.damaged': { zh: "受损", en: "Damaged" },
  'dmg.outcome.fire': { zh: "起火", en: "On Fire" },
  'dmg.outcome.turret': { zh: "炮塔受损", en: "Turret Hit" },
  'dmg.outcome.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'dmg.outcome.crewCheck': { zh: "阵亡检定", en: "Crew Check" },
  'crew.role.1': { zh: "车长", en: "Commander" },
  'crew.role.2': { zh: "装填手", en: "Loader" },
  'crew.role.3': { zh: "炮手", en: "Gunner" },
  'crew.role.4': { zh: "驾驶员", en: "Driver" },
  'crew.role.5': { zh: "副驾驶", en: "Co-driver" },
  'crew.death.falseAlarmHatch': { zh: "虚惊（舱盖关）", en: "False Alarm (Hatch Closed)" },
  'crew.death.falseAlarm': { zh: "乘员虚惊", en: "Crew False Alarm" },
  'crew.death.kia': { zh: "{role} 阵亡", en: "{role} KIA" },
  'unit.status.destroyed': { zh: "已毁", en: "Destroyed" },
  'unit.status.fire': { zh: "起火", en: "On Fire" },
  'hud.init': { zh: "回合 - | 行动力 -/-", en: "Turn - | AP -/-" },
  'hud.enemyTurn': { zh: "回合 {n} | 敌方行动中...", en: "Turn {n} | Enemy acting..." },
  'hud.playerChoose': { zh: "回合 {n} | 玩家 | 选择阶段  {tags}", en: "Turn {n} | Player | Choose phase  {tags}" },
  'hud.movePhase': { zh: "回合 {n} | 移动阶段 | 骰子 {dice}", en: "Turn {n} | Move phase | Dice {dice}" },
  'hud.attackPhase': { zh: "回合 {n} | 攻击阶段 | {loaded} | 骰子 {dice}{sel}", en: "Turn {n} | Attack phase | {loaded} | Dice {dice}{sel}" },
  'hud.attackSelectHint': { zh: "点敌人开火", en: "Click enemy to fire" },
  'hud.loaded': { zh: "已装填", en: "Loaded" },
  'hud.unloaded': { zh: "未装填", en: "Unloaded" },
  'hud.moveDone': { zh: "✓移动", en: "✓Move" },
  'hud.moveTodo': { zh: "·移动", en: "·Move" },
  'hud.attackDone': { zh: "✓攻击", en: "✓Attack" },
  'hud.attackTodo': { zh: "·攻击", en: "·Attack" },
  'btn.nextPhase': { zh: "下一阶段", en: "Next Phase" },
  'btn.endTurn': { zh: "结束回合", en: "End Turn" },
  'btn.enemyTurnRunning': { zh: "敌方回合中", en: "Enemy Turn" },
  'btn.save': { zh: "存档", en: "Save" },
  'btn.load': { zh: "读档", en: "Load" },
  'btn.restart': { zh: "再来一局", en: "Play Again" },
  'btn.movePhase': { zh: "移动阶段", en: "Move Phase" },
  'btn.attackPhase': { zh: "攻击阶段", en: "Attack Phase" },
  'outcome.win': { zh: "胜利！", en: "Victory!" },
  'outcome.lose': { zh: "战败", en: "Defeat" },
  'status.panelTitle': { zh: "谢尔曼状态", en: "Sherman Status" },
  'status.row.loaded': { zh: "装填", en: "Loaded" },
  'status.row.hatch': { zh: "舱盖", en: "Hatch" },
  'status.row.fire': { zh: "车体", en: "Hull" },
  'status.row.turret': { zh: "炮塔", en: "Turret" },
  'status.row.mobility': { zh: "机动", en: "Mobility" },
  'status.row.crewTitle': { zh: "乘员", en: "Crew" },
  'status.crew.1': { zh: "① 车长", en: "① Commander" },
  'status.crew.2': { zh: "② 装填手", en: "② Loader" },
  'status.crew.3': { zh: "③ 炮手", en: "③ Gunner" },
  'status.crew.4': { zh: "④ 驾驶员", en: "④ Driver" },
  'status.crew.5': { zh: "⑤ 副驾驶", en: "⑤ Co-driver" },
  'status.val.loaded': { zh: "已装填", en: "Loaded" },
  'status.val.unloaded': { zh: "未装填", en: "Unloaded" },
  'status.val.hatchOpen': { zh: "打开", en: "Open" },
  'status.val.hatchClosed': { zh: "关闭", en: "Closed" },
  'status.val.destroyed': { zh: "已毁", en: "Destroyed" },
  'status.val.fireN': { zh: "起火({n})", en: "Fire({n})" },
  'status.val.damaged': { zh: "受损", en: "Damaged" },
  'status.val.intact': { zh: "完好", en: "Intact" },
  'status.val.paralyzed': { zh: "瘫痪", en: "Immobilized" },
  'status.val.normal': { zh: "正常", en: "Normal" },
  'status.val.crewDead': { zh: "阵亡", en: "KIA" },
  'status.val.crewAlive': { zh: "存活", en: "Alive" },
  'dice.tray.move': { zh: "移动阶段骰子（点骰子选择动作）", en: "Move Phase Dice (tap a die to act)" },
  'dice.tray.attack': { zh: "攻击阶段骰子（点骰子选择动作）", en: "Attack Phase Dice (tap a die to act)" },
  'dice.slot.used': { zh: "已用", en: "Used" },
  'die.hint.turn': { zh: "转向", en: "Turn" },
  'die.hint.drive': { zh: "前进", en: "Advance" },
  'die.hint.reverse': { zh: "后退", en: "Reverse" },
  'die.hint.start': { zh: "启动", en: "Start" },
  'floater.hatchLocked': { zh: "本回合舱盖已锁定", en: "Hatch locked this turn" },
  'floater.hatchCommanderDead': { zh: "车长已阵亡，操作无效", en: "Commander is dead; action invalid" },
  'die.hint.reload': { zh: "装填", en: "Reload" },
  'die.hint.gun': { zh: "主炮", en: "Gun" },
  'die.hint.mg': { zh: "机枪", en: "MG" },
  'die.hint.none': { zh: "—", en: "—" },
  'action.turnCW': { zh: "↻ 顺时针 60°", en: "↻ CW 60°" },
  'action.turnCCW': { zh: "↺ 逆时针 60°", en: "↺ CCW 60°" },
  'action.advance': { zh: "▲ 前进 1 格", en: "▲ Advance 1" },
  'action.reverse': { zh: "▼ 后退 1 格", en: "▼ Reverse 1" },
  'action.skip': { zh: "放弃本骰", en: "Skip Die" },
  'action.reload': { zh: "装填主炮", en: "Reload Gun" },
  'action.fire': { zh: "选定主炮开火", en: "Fire Gun" },
  'floater.noFacing': { zh: "未定朝向", en: "No Facing" },
  'floater.blockedTerrain': { zh: "地形阻挡", en: "Blocked Terrain" },
  'floater.enemyBlock': { zh: "敌方占据", en: "Enemy Blocks" },
  'floater.smoke': { zh: "烟雾", en: "Smoke" },
  'floater.repair': { zh: "修复", en: "Repair" },
  'attack.reason.selfFire': { zh: "不能攻击自己", en: "Cannot Target Self" },
  'attack.reason.destroyedTarget': { zh: "目标已被摧毁", en: "Target Destroyed" },
  'attack.reason.overlap': { zh: "目标重叠", en: "Overlap" },
  'attack.reason.notStraight': { zh: "非六向直线", en: "Not on Hex Axis" },
  'attack.reason.notStraightHint': { zh: "需在六向直线上", en: "Must be on hex axis" },
  'attack.reason.blocked': { zh: "无视线", en: "No LOS" },
  'attack.reason.unknown': { zh: "无法攻击", en: "Cannot Attack" },
  'preview.impossible': { zh: "≥{n}\\n几乎不可能", en: "≥{n}\\nImpossible" },
  'dice.panel.hitNeed': { zh: "命中需 ≥{n}", en: "Hit ≥{n}" },
  'dice.panel.hitYes': { zh: "命中！", en: "Hit!" },
  'dice.panel.hitNo': { zh: "未命中", en: "Miss" },
  'dice.panel.penMustPen': { zh: "必穿 (≤0)", en: "Auto-Pen (≤0)" },
  'dice.panel.penCantPen': { zh: "不可击穿 (≥7)", en: "Immune (≥7)" },
  'dice.panel.penNeed': { zh: "需 ≥{n}", en: "Need ≥{n}" },
  'dice.panel.penYes': { zh: "击穿！", en: "Penetrate!" },
  'dice.panel.penNo': { zh: "跳弹", en: "Ricochet" },
  'dice.panel.dmgTitle': { zh: "伤害检定", en: "Damage Check" },
  'dice.panel.crewTitle': { zh: "阵亡检定", en: "Crew Check" },
  'dice.panel.outcomeMiss': { zh: "MISS", en: "MISS" },
  'dice.panel.outcomeRic': { zh: "跳弹", en: "Ricochet" },
  'actor.player': { zh: "玩家", en: "Player" },
  'actor.sherman': { zh: "谢尔曼", en: "Sherman" },
  'actor.enemyPrefix': { zh: "敌方 {name}", en: "Enemy {name}" },
  'dice.aiHeader': { zh: "{col}  {n}骰", en: "{col}  {n}d" },
};
