/**
 * Tank presentation database. Auto-generated; do not edit this file.
 *
 * Source: data/tank_visuals.csv
 * Rebuild: node tools/buildTankVisualDB.js
 */

import { UnitKind } from './types';

export type TankVisualKind = Extract<UnitKind, 'sherman' | 'sherman76' | 't34' | 'tiger' | 'tigerking' | 'maus' | 'panzer4' | 'stug3' | 'panzer3' | 'type97' | 'type95' | 'type4' | 'at_gun' | 'heavy_artillery' | 'german_heavy_artillery' | 'truck'>;
export type SplitTankKind = Extract<UnitKind, 'sherman' | 'sherman76' | 't34' | 'tiger' | 'tigerking' | 'maus' | 'panzer4' | 'panzer3' | 'type97' | 'type95' | 'type4'>;
export const TANK_VISUAL_KINDS: readonly TankVisualKind[] = ['sherman', 'sherman76', 't34', 'tiger', 'tigerking', 'maus', 'panzer4', 'stug3', 'panzer3', 'type97', 'type95', 'type4', 'at_gun', 'heavy_artillery', 'german_heavy_artillery', 'truck'];
export const SPLIT_TANK_KINDS: readonly SplitTankKind[] = ['sherman', 'sherman76', 't34', 'tiger', 'tigerking', 'maus', 'panzer4', 'panzer3', 'type97', 'type95', 'type4'];
export const EMPTY_COMMANDER_HATCH_SPRITE_SIZE = 20;
export const SHERMAN_EMPTY_COMMANDER_HATCH_SCALE = 0.5;

export interface TankVisualAssetConfig {
  topSpritePath: string;
  hullSpritePath: string;
  turretSpritePath: string;
  destroyedSpritePath: string;
}

export interface TankVisualConfig {
  fitScale: number;
  offsetForward: number;
  offsetRight: number;
  aspectRatioMul: number;
  muzzle: { spriteX: number; spriteY: number };
  destroyedOffsetForward: number;
  destroyedOffsetRight: number;
  destroyedFitScale: number;
}

export interface SplitTankVisualConfig {
  hullFitScale: number;
  turretScale: number;
  hullOffsetForward: number;
  hullOffsetRight: number;
  turretOffsetForward: number;
  turretOffsetRight: number;
  commanderHatchSpriteX: number;
  commanderHatchSpriteY: number;
  commanderHatchScale: number;
}

export interface SplitTankGeometryConfig {
  topTrim: { x: number; y: number; w: number; h: number };
  turretTrim: { x: number; y: number; w: number; h: number };
  pivot: { bodyX: number; bodyY: number; spriteX: number; spriteY: number };
  muzzle: { spriteX: number; spriteY: number };
}

const TANK_VISUAL_DEFAULT: TankVisualConfig = {
  fitScale: 1,
  offsetForward: 0,
  offsetRight: 0,
  aspectRatioMul: 1,
  muzzle: { spriteX: 0, spriteY: 0 },
  destroyedOffsetForward: 0,
  destroyedOffsetRight: 0,
  destroyedFitScale: 1,
};

const TANK_VISUAL_ASSET_CONFIG: Record<TankVisualKind, TankVisualAssetConfig> = {
  sherman: { topSpritePath: "textures/units/sherman_top/spriteFrame", hullSpritePath: "textures/units/sherman_top_hull/spriteFrame", turretSpritePath: "textures/units/sherman_top_turret/spriteFrame", destroyedSpritePath: "textures/units/sherman_top_destroyed/spriteFrame" },
  sherman76: { topSpritePath: "textures/units/sherman76_top/spriteFrame", hullSpritePath: "textures/units/sherman76_top_hull/spriteFrame", turretSpritePath: "textures/units/sherman76_top_turret/spriteFrame", destroyedSpritePath: "textures/units/sherman76_top_destroyed/spriteFrame" },
  t34: { topSpritePath: "textures/units/t34_top/spriteFrame", hullSpritePath: "textures/units/t34_top_hull/spriteFrame", turretSpritePath: "textures/units/t34_top_turret/spriteFrame", destroyedSpritePath: "textures/units/t34_top_destroyed/spriteFrame" },
  tiger: { topSpritePath: "textures/units/tiger_top/spriteFrame", hullSpritePath: "textures/units/tiger_top_hull/spriteFrame", turretSpritePath: "textures/units/tiger_top_turret/spriteFrame", destroyedSpritePath: "textures/units/tiger_top_destroyed/spriteFrame" },
  tigerking: { topSpritePath: "textures/units/tigerking_top/spriteFrame", hullSpritePath: "textures/units/tigerking_top_hull/spriteFrame", turretSpritePath: "textures/units/tigerking_top_turret/spriteFrame", destroyedSpritePath: "textures/units/tigerking_top_destroyed/spriteFrame" },
  maus: { topSpritePath: "textures/units/maus_top/spriteFrame", hullSpritePath: "textures/units/maus_top_hull/spriteFrame", turretSpritePath: "textures/units/maus_top_turret/spriteFrame", destroyedSpritePath: "textures/units/maus_top_destroyed/spriteFrame" },
  panzer4: { topSpritePath: "textures/units/panzer4_top/spriteFrame", hullSpritePath: "textures/units/panzer4_top_hull/spriteFrame", turretSpritePath: "textures/units/panzer4_top_turret/spriteFrame", destroyedSpritePath: "textures/units/panzer4_top_destroyed/spriteFrame" },
  stug3: { topSpritePath: "textures/units/stug3_top/spriteFrame", hullSpritePath: "", turretSpritePath: "", destroyedSpritePath: "textures/units/stug3_top_destroyed/spriteFrame" },
  panzer3: { topSpritePath: "textures/units/panzer3_top/spriteFrame", hullSpritePath: "textures/units/panzer3_top_hull/spriteFrame", turretSpritePath: "textures/units/panzer3_top_turret/spriteFrame", destroyedSpritePath: "textures/units/panzer3_top_destroyed/spriteFrame" },
  type97: { topSpritePath: "textures/units/type97_top_hull/spriteFrame", hullSpritePath: "textures/units/type97_top_hull/spriteFrame", turretSpritePath: "textures/units/type97_top_turret/spriteFrame", destroyedSpritePath: "textures/units/type97_top_destroyed/spriteFrame" },
  type95: { topSpritePath: "textures/units/type95_top_hull/spriteFrame", hullSpritePath: "textures/units/type95_top_hull/spriteFrame", turretSpritePath: "textures/units/type95_top_turret/spriteFrame", destroyedSpritePath: "textures/units/type95_top_destroyed/spriteFrame" },
  type4: { topSpritePath: "textures/units/type4_top/spriteFrame", hullSpritePath: "textures/units/type4_top_hull/spriteFrame", turretSpritePath: "textures/units/type4_top_turret/spriteFrame", destroyedSpritePath: "textures/units/type4_top_destroyed/spriteFrame" },
  at_gun: { topSpritePath: "textures/units/at_gun_top/spriteFrame", hullSpritePath: "", turretSpritePath: "", destroyedSpritePath: "textures/units/at_gun_top_destroyed/spriteFrame" },
  heavy_artillery: { topSpritePath: "textures/units/heavy_artillery_top/spriteFrame", hullSpritePath: "", turretSpritePath: "", destroyedSpritePath: "textures/units/heavy_artillery_top_destroyed/spriteFrame" },
  german_heavy_artillery: { topSpritePath: "textures/units/german_coastal_bunker_top/spriteFrame", hullSpritePath: "", turretSpritePath: "", destroyedSpritePath: "textures/units/german_coastal_bunker_top_destroyed/spriteFrame" },
  truck: { topSpritePath: "textures/units/truck_top/spriteFrame", hullSpritePath: "", turretSpritePath: "", destroyedSpritePath: "textures/units/truck_top_destroyed/spriteFrame" },
};

const TANK_VISUAL_CONFIG: Record<TankVisualKind, TankVisualConfig> = {
  sherman: { fitScale: 0.76, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 14 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  sherman76: { fitScale: 0.76, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 14 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  t34: { fitScale: 0.76, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 24 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  tiger: { fitScale: 0.9, offsetForward: 0.1, offsetRight: 0, aspectRatioMul: 1.1, muzzle: { spriteX: 0, spriteY: 18 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  tigerking: { fitScale: 0.78, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 26 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  maus: { fitScale: 0.9, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 17 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  panzer4: { fitScale: 0.7, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 19 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  stug3: { fitScale: 0.8, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 1, spriteY: 24 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  panzer3: { fitScale: 0.66, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 20 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  type97: { fitScale: 0.7, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 14 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  type95: { fitScale: 0.6, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 21 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  type4: { fitScale: 0.7, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 1, spriteY: 25 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  at_gun: { fitScale: 0.6, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 1, spriteY: 25 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  heavy_artillery: { fitScale: 0.85, offsetForward: 0.11, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 1, spriteY: 35 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
  german_heavy_artillery: { fitScale: 0.85, offsetForward: 0.08, offsetRight: -0.015, aspectRatioMul: 1, muzzle: { spriteX: 1, spriteY: 33 }, destroyedOffsetForward: -0.07, destroyedOffsetRight: 0, destroyedFitScale: 0.83 },
  truck: { fitScale: 0.8, offsetForward: 0, offsetRight: 0, aspectRatioMul: 1, muzzle: { spriteX: 0, spriteY: 0 }, destroyedOffsetForward: 0, destroyedOffsetRight: 0, destroyedFitScale: 1 },
};

const SPLIT_TANK_VISUAL_CONFIG: Record<SplitTankKind, SplitTankVisualConfig> = {
  sherman: { hullFitScale: 0.7, turretScale: 1.31, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: -0.01, turretOffsetRight: 0, commanderHatchSpriteX: 38, commanderHatchSpriteY: 9, commanderHatchScale: 14 },
  sherman76: { hullFitScale: 0.7, turretScale: 1.2, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0.04, turretOffsetRight: 0, commanderHatchSpriteX: 51, commanderHatchSpriteY: 10, commanderHatchScale: 14 },
  t34: { hullFitScale: 0.7, turretScale: 0.6, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0, turretOffsetRight: 0, commanderHatchSpriteX: 72, commanderHatchSpriteY: 25, commanderHatchScale: 22 },
  tiger: { hullFitScale: 0.6755, turretScale: 1.2, hullOffsetForward: 0, hullOffsetRight: -0.01, turretOffsetForward: 0.07, turretOffsetRight: 0.004, commanderHatchSpriteX: 71, commanderHatchSpriteY: 25, commanderHatchScale: 17 },
  tigerking: { hullFitScale: 0.85, turretScale: 1, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: -0.02, turretOffsetRight: 0.01, commanderHatchSpriteX: 96, commanderHatchSpriteY: 31, commanderHatchScale: 16 },
  maus: { hullFitScale: 1.1, turretScale: 1, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0.02, turretOffsetRight: -0.01, commanderHatchSpriteX: 69, commanderHatchSpriteY: 23, commanderHatchScale: 13 },
  panzer4: { hullFitScale: 0.7, turretScale: 0.92, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0, turretOffsetRight: 0, commanderHatchSpriteX: 46, commanderHatchSpriteY: 19, commanderHatchScale: 19 },
  panzer3: { hullFitScale: 0.6, turretScale: 0.9, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0.01, turretOffsetRight: 0, commanderHatchSpriteX: 52, commanderHatchSpriteY: 20, commanderHatchScale: 23 },
  type97: { hullFitScale: 0.65, turretScale: 1, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: -0.015, turretOffsetRight: 0, commanderHatchSpriteX: 47, commanderHatchSpriteY: 9, commanderHatchScale: 18 },
  type95: { hullFitScale: 0.55, turretScale: 0.65, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0.01, turretOffsetRight: -0.025, commanderHatchSpriteX: 46, commanderHatchSpriteY: 30, commanderHatchScale: 28 },
  type4: { hullFitScale: 0.72, turretScale: 1.1, hullOffsetForward: 0, hullOffsetRight: 0, turretOffsetForward: 0.07, turretOffsetRight: -0.003, commanderHatchSpriteX: 48, commanderHatchSpriteY: 28, commanderHatchScale: 14 },
};

const SPLIT_TANK_GEOMETRY_CONFIG: Record<SplitTankKind, SplitTankGeometryConfig> = {
  sherman: {
    topTrim: { x: 0, y: 0, w: 100, h: 44 },
    turretTrim: { x: 0, y: 0, w: 52, h: 29 },
    pivot: { bodyX: 48, bodyY: 21, spriteX: 35, spriteY: 14 },
    muzzle: { spriteX: 0, spriteY: 14 },
  },
  sherman76: {
    topTrim: { x: 0, y: 0, w: 100, h: 44 },
    turretTrim: { x: 0, y: 0, w: 72, h: 29 },
    pivot: { bodyX: 48, bodyY: 22, spriteX: 48, spriteY: 14 },
    muzzle: { spriteX: 0, spriteY: 14 },
  },
  t34: {
    topTrim: { x: 0, y: 0, w: 100, h: 50 },
    turretTrim: { x: 0, y: 0, w: 100, h: 50 },
    pivot: { bodyX: 42, bodyY: 25, spriteX: 70, spriteY: 25 },
    muzzle: { spriteX: 0, spriteY: 24 },
  },
  tiger: {
    topTrim: { x: 0, y: 0, w: 100, h: 66 },
    turretTrim: { x: 0, y: 0, w: 100, h: 37 },
    pivot: { bodyX: 49, bodyY: 33, spriteX: 65, spriteY: 18 },
    muzzle: { spriteX: 0, spriteY: 18 },
  },
  tigerking: {
    topTrim: { x: 0, y: 0, w: 100, h: 50 },
    turretTrim: { x: 0, y: 0, w: 120, h: 50 },
    pivot: { bodyX: 51, bodyY: 25, spriteX: 94, spriteY: 25 },
    muzzle: { spriteX: 0, spriteY: 26 },
  },
  maus: {
    topTrim: { x: 0, y: 0, w: 100, h: 38 },
    turretTrim: { x: 0, y: 0, w: 96, h: 34 },
    pivot: { bodyX: 59, bodyY: 19, spriteX: 68, spriteY: 18 },
    muzzle: { spriteX: 0, spriteY: 17 },
  },
  panzer4: {
    topTrim: { x: 0, y: 0, w: 100, h: 50 },
    turretTrim: { x: 0, y: 0, w: 66, h: 39 },
    pivot: { bodyX: 50, bodyY: 25, spriteX: 36, spriteY: 19 },
    muzzle: { spriteX: 0, spriteY: 19 },
  },
  panzer3: {
    topTrim: { x: 0, y: 0, w: 100, h: 53 },
    turretTrim: { x: 0, y: 0, w: 79, h: 40 },
    pivot: { bodyX: 42, bodyY: 26, spriteX: 41, spriteY: 20 },
    muzzle: { spriteX: 0, spriteY: 20 },
  },
  type97: {
    topTrim: { x: 0, y: 0, w: 100, h: 42 },
    turretTrim: { x: 0, y: 0, w: 64, h: 27 },
    pivot: { bodyX: 44, bodyY: 18, spriteX: 46, spriteY: 14 },
    muzzle: { spriteX: 0, spriteY: 14 },
  },
  type95: {
    topTrim: { x: 0, y: 0, w: 100, h: 51 },
    turretTrim: { x: 0, y: 0, w: 79, h: 43 },
    pivot: { bodyX: 47, bodyY: 29, spriteX: 45, spriteY: 29 },
    muzzle: { spriteX: 0, spriteY: 21 },
  },
  type4: {
    topTrim: { x: 0, y: 0, w: 100, h: 50 },
    turretTrim: { x: 0, y: 0, w: 100, h: 50 },
    pivot: { bodyX: 45, bodyY: 25, spriteX: 45, spriteY: 25 },
    muzzle: { spriteX: 1, spriteY: 25 },
  },
};

export function tankVisualAssetConfigOf(kind: TankVisualKind): TankVisualAssetConfig {
  return TANK_VISUAL_ASSET_CONFIG[kind];
}

export function tankVisualConfigOf(kind: UnitKind): TankVisualConfig {
  if (kind === 'sherman' || kind === 'sherman76' || kind === 't34' || kind === 'tiger' || kind === 'tigerking' || kind === 'maus' || kind === 'panzer4' || kind === 'stug3' || kind === 'panzer3' || kind === 'type97' || kind === 'type95' || kind === 'type4' || kind === 'at_gun' || kind === 'heavy_artillery' || kind === 'german_heavy_artillery' || kind === 'truck') {
    return TANK_VISUAL_CONFIG[kind];
  }
  return TANK_VISUAL_DEFAULT;
}

export function splitTankVisualConfigOf(kind: SplitTankKind): SplitTankVisualConfig {
  return SPLIT_TANK_VISUAL_CONFIG[kind];
}

export function splitTankGeometryConfigOf(kind: SplitTankKind): SplitTankGeometryConfig {
  return SPLIT_TANK_GEOMETRY_CONFIG[kind];
}

/** Commander overlay scale after all tank-specific source-space transforms. */
export function commanderHatchRenderedScaleCoefficient(kind: SplitTankKind): number {
  return commanderHatchRenderedScaleCoefficientForConfig(
    splitTankVisualConfigOf(kind),
    splitTankGeometryConfigOf(kind),
  );
}

export function commanderHatchRenderedScaleCoefficientForConfig(
  visual: Pick<SplitTankVisualConfig, 'commanderHatchScale' | 'hullFitScale' | 'turretScale'>,
  geometry: Pick<SplitTankGeometryConfig, 'topTrim'>,
): number {
  const sourceMax = Math.max(geometry.topTrim.w, geometry.topTrim.h) || 1;
  return visual.commanderHatchScale * visual.hullFitScale * visual.turretScale / sourceMax;
}

/** Scale a shared empty-hatch sprite relative to Sherman's approved value. */
export function emptyCommanderHatchScaleOf(
  kind: SplitTankKind,
  shermanEmptyScale = SHERMAN_EMPTY_COMMANDER_HATCH_SCALE,
): number {
  const shermanScale = commanderHatchRenderedScaleCoefficient('sherman');
  if (shermanScale <= 0) return shermanEmptyScale;
  return shermanEmptyScale * commanderHatchRenderedScaleCoefficient(kind) / shermanScale;
}
