/**
 * Unit data DB - generated automatically. Do not edit this file by hand.
 *
 * Source: data/units.csv
 * Regenerate: node tools/buildUnitDB.js
 */

import { Theater, UnitKind, UnitStats } from './types';

const DB: Record<UnitKind, UnitStats> = {
  sherman: { // 谢尔曼 M4 - 玩家方坦克；Pacific profile 由 UnitDB 覆盖为 4/11/10/9/8/AP2
    faction: "allied",
    size: 4, armorFront: 11, armorFrontSide: 10, armorRearSide: 9, armorRear: 8, penetration: 2, usCasualtyDice: 0,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  tiger: { // 虎式 - 重型敌方坦克
    faction: "german",
    size: 3, armorFront: 12, armorFrontSide: 11, armorRearSide: 10, armorRear: 9, penetration: 3, usCasualtyDice: 0,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  panzer4: { // 四号坦克 - 中坚敌方坦克
    faction: "german",
    size: 4, armorFront: 11, armorFrontSide: 10, armorRearSide: 9, armorRear: 8, penetration: 2, usCasualtyDice: 0,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  panzer3: { // 三号坦克 - 次级敌方坦克
    faction: "german",
    size: 5, armorFront: 10, armorFrontSide: 9, armorRearSide: 8, armorRear: 7, penetration: 1, usCasualtyDice: 0,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  truck: { // 卡车 - 占位 - 后续按特殊规则结算
    faction: "german",
    size: 3, armorFront: 2, armorFrontSide: 2, armorRearSide: 2, armorRear: 2, penetration: 0, usCasualtyDice: 0,
    moveSound: "audio/tank_move",
    attackSound: "",
    infantryTankCoordination: 0,
  },
  infantry: { // 步兵 - 占位 - 仅事件中作为攻击方
    faction: "german",
    size: 2, armorFront: 0, armorFrontSide: 0, armorRearSide: 0, armorRear: 0, penetration: 3, usCasualtyDice: 0,
    moveSound: "",
    attackSound: "",
    infantryTankCoordination: 0,
  },
  officer: { // 军官 - 任务 8：高级军官（与步兵同属徒步类，但 kind 独立避免与 spawn 步兵混淆）
    faction: "german",
    size: 0, armorFront: 0, armorFrontSide: 0, armorRearSide: 0, armorRear: 0, penetration: 1, usCasualtyDice: 0,
    moveSound: "",
    attackSound: "",
    infantryTankCoordination: 0,
  },
  type95: { // 九五式轻战车 - Pacific D11: Type 95 Ha-Go
    faction: "japanese",
    size: 4, armorFront: 11, armorFrontSide: 10, armorRearSide: 9, armorRear: 8, penetration: 0, usCasualtyDice: 1,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  type97: { // 九七式中战车 - Pacific: Type 97 Chi-Ha
    faction: "japanese",
    size: 4, armorFront: 9, armorFrontSide: 8, armorRearSide: 8, armorRear: 7, penetration: 1, usCasualtyDice: 2,
    moveSound: "audio/tank_move",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 1,
  },
  at_gun: { // 反坦克炮 - Pacific: AT Gun
    faction: "japanese",
    size: 5, armorFront: 8, armorFrontSide: 8, armorRearSide: 7, armorRear: 6, penetration: 2, usCasualtyDice: 1,
    moveSound: "",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 0,
  },
  japanese_infantry: { // 日本步兵 - Pacific: Japanese Infantry
    faction: "japanese",
    size: 2, armorFront: 0, armorFrontSide: 0, armorRearSide: 0, armorRear: 0, penetration: 3, usCasualtyDice: 1,
    moveSound: "",
    attackSound: "",
    infantryTankCoordination: 0,
  },
  heavy_artillery: { // 重炮 - Pacific: Heavy Artillery
    faction: "japanese",
    size: 4, armorFront: 10, armorFrontSide: 9, armorRearSide: 7, armorRear: 6, penetration: 4, usCasualtyDice: 2,
    moveSound: "",
    attackSound: "audio/cannon_fire",
    infantryTankCoordination: 0,
  },
};

const PACIFIC_OVERRIDES: Partial<Record<UnitKind, Partial<UnitStats>>> = {
  sherman: {
    size: 4, armorFront: 11, armorFrontSide: 10, armorRearSide: 9, armorRear: 8, penetration: 2, usCasualtyDice: 0,
  },
};

export function getUnitStats(kind: UnitKind, theater: Theater = 'europe'): UnitStats {
  const base = DB[kind];
  const override = theater === 'pacific' ? PACIFIC_OVERRIDES[kind] : undefined;
  return { ...base, ...(override ?? {}) };
}
